var $pg_logging=!1;if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){var c,d;if(this==null)throw new TypeError("this is null or not defined");var e=Object(this),f=e.length>>>0;if({}.toString.call(a)=="[object Function]"){b&&(c=b);for(d=0;d<f;){var h;d in e&&(h=e[d],a.call(c,h,d,e));d++}}};
if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a){if(this==null)throw new TypeError;var b=Object(this),c=b.length>>>0;if(c===0)return-1;var d=0;arguments.length>0&&(d=Number(arguments[1]),d!=d?d=0:d!=0&&d!=Infinity&&d!=-Infinity&&(d=(d>0||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=d>=0?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};
if(!String.prototype.startsWith)String.prototype.startsWith=function(a){return this.slice(0,a.length)==a};if(!window.Node)var Node={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12};
if(!window.Node.TEXT_NODE)Node.ELEMENT_NODE=1,Node.ATTRIBUTE_NODE=2,Node.TEXT_NODE=3,Node.CDATA_SECTION_NODE=4,Node.ENTITY_REFERENCE_NODE=5,Node.ENTITY_NODE=6,Node.PROCESSING_INSTRUCTION_NODE=7,Node.COMMENT_NODE=8,Node.DOCUMENT_NODE=9,Node.DOCUMENT_TYPE_NODE=10,Node.DOCUMENT_FRAGMENT_NODE=11,Node.NOTATION_NODE=12;function addListener(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)}
(function(){if(!document.querySelectorAll&&!document.querySelector&&typeof document.createStyleSheet!="undefined"){var a=document.createStyleSheet(),b=function(b,d){var e=document.all,f=e.length,h,g=[];a.addRule(b,"foo:bar");for(h=0;h<f;h+=1)if(e[h].currentStyle.foo==="bar"&&(g.push(e[h]),g.length>d))break;a.removeRule(0);return g};document.querySelectorAll=function(a){return b(a,Infinity)};document.querySelector=function(a){return b(a,1)[0]||null}}})();var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=g[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var j,e,g,u,q=f,o,m=d[a];if(Object.prototype.toString.apply(m)==="[object Array]")j=Array.prototype.toJSON,delete Array.prototype.toJSON;m&&typeof m==="object"&&typeof m.toJSON==="function"&&(m=m.toJSON(a));if(j)Array.prototype.toJSON=j;typeof l==="function"&&
(m=l.call(d,a,m));switch(typeof m){case "string":return b(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";f+=h;o=[];if(Object.prototype.toString.apply(m)==="[object Array]"){u=m.length;for(j=0;j<u;j+=1)o[j]=c(j,m)||"null";g=o.length===0?"[]":f?"[\n"+f+o.join(",\n"+f)+"\n"+q+"]":"["+o.join(",")+"]";f=q;return g}if(l&&typeof l==="object"){u=l.length;for(j=0;j<u;j+=1)typeof l[j]==="string"&&(e=l[j],(g=c(e,m))&&o.push(b(e)+
(f?": ":":")+g))}else for(e in m)Object.prototype.hasOwnProperty.call(m,e)&&(g=c(e,m))&&o.push(b(e)+(f?": ":":")+g);g=o.length===0?"{}":f?"{\n"+f+o.join(",\n"+f)+"\n"+q+"}":"{"+o.join(",")+"}";f=q;return g}}window.Prototype&&(typeof Object!=="undefined"&&Object.prototype&&Object.prototype.toJSON&&delete Object.prototype.toJSON,typeof Array!=="undefined"&&Array.prototype&&Array.prototype.toJSON&&delete Array.prototype.toJSON,typeof Hash!=="undefined"&&Hash.prototype&&Hash.prototype.toJSON&&delete Hash.prototype.toJSON,
typeof String!=="undefined"&&String.prototype&&String.prototype.toJSON&&delete String.prototype.toJSON,typeof Date!=="undefined"&&Date.prototype&&Date.prototype.toJSON&&delete Date.prototype.toJSON,typeof Boolean!=="undefined"&&Boolean.prototype&&Boolean.prototype.toJSON&&delete Boolean.prototype.toJSON,typeof Number!=="undefined"&&Number.prototype&&Number.prototype.toJSON&&delete Number.prototype.toJSON);if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?
this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,h,g={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,b,d){var e;h=f="";if(typeof d==="number")for(e=0;e<d;e+=1)h+=" ";else typeof d==="string"&&(h=d);if((l=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return c("",{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var e,f,h=a[d];if(h&&typeof h==="object")for(e in h)Object.prototype.hasOwnProperty.call(h,
e)&&(f=c(h,e),f!==void 0?h[e]=f:delete h[e]);return b.call(a,d,h)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}})();
function xml2json(a){var b={toObj:function(a){var d={};if(a.nodeType==1){if(a.attributes.length)for(var e=0;e<a.attributes.length;e++)d["@"+a.attributes[e].nodeName]=b.escape((a.attributes[e].nodeValue||"").toString());if(a.firstChild){for(var f=e=0,h=!1,g=a.firstChild;g;g=g.nextSibling)g.nodeType==1?h=!0:g.nodeType==3&&g.nodeValue.match(/[^ \f\n\r\t\v]/)?e++:g.nodeType==4&&f++;if(h)if(e<2&&f<2){b.removeWhite(a);for(g=a.firstChild;g;g=g.nextSibling)g.nodeType==3?d["#text"]=b.escape(g.nodeValue):g.nodeType==
4?d["#cdata"]=b.escape(g.nodeValue):d[g.nodeName]?d[g.nodeName]instanceof Array?d[g.nodeName][d[g.nodeName].length]=b.toObj(g):d[g.nodeName]=[d[g.nodeName],b.toObj(g)]:d[g.nodeName]=b.toObj(g)}else a.attributes.length?d["#text"]=b.escape(b.innerXml(a)):d=b.escape(b.innerXml(a));else if(e)a.attributes.length?d["#text"]=b.escape(b.innerXml(a)):d=b.escape(b.innerXml(a));else if(f)if(f>1)d=b.escape(b.innerXml(a));else for(g=a.firstChild;g;g=g.nextSibling)d["#cdata"]=b.escape(g.nodeValue)}!a.attributes.length&&
!a.firstChild&&(d=null)}else a.nodeType==9&&(d=b.toObj(a.documentElement));return d},toJson:function(a,d,e){var f=d?'"'+d+'"':"";if(a instanceof Array){for(var h=0,g=a.length;h<g;h++)a[h]=b.toJson(a[h],"",e+"\t");f+=(d?":[":"[")+(a.length>1?"\n"+e+"\t"+a.join(",\n"+e+"\t")+"\n"+e:a.join(""))+"]"}else if(a==null)f+=(d&&":")+"null";else if(typeof a=="object"){h=[];for(g in a)h[h.length]=b.toJson(a[g],g,e+"\t");f+=(d?":{":"{")+(h.length>1?"\n"+e+"\t"+h.join(",\n"+e+"\t")+"\n"+e:h.join(""))+"}"}else f+=
typeof a=="string"?(d&&":")+'"'+a.toString()+'"':(d&&":")+a.toString();return f},innerXml:function(a){var b="";if("innerHTML"in a)b=a.innerHTML;else for(var e=function(a){var b="";if(a.nodeType==1){b+="<"+a.nodeName;for(var c=0;c<a.attributes.length;c++)b+=" "+a.attributes[c].nodeName+'="'+(a.attributes[c].nodeValue||"").toString()+'"';if(a.firstChild){b+=">";for(c=a.firstChild;c;c=c.nextSibling)b+=e(c);b+="</"+a.nodeName+">"}else b+="/>"}else a.nodeType==3?b+=a.nodeValue:a.nodeType==4&&(b+="<![CDATA["+
a.nodeValue+"]]\>");return b},a=a.firstChild;a;a=a.nextSibling)b+=e(a);return b},escape:function(a){return a.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(a){a.normalize();for(var d=a.firstChild;d;)if(d.nodeType==3)if(d.nodeValue.match(/[^ \f\n\r\t\v]/))d=d.nextSibling;else{var e=d.nextSibling;a.removeChild(d);d=e}else d.nodeType==1&&b.removeWhite(d),d=d.nextSibling;return a}};if(a.nodeType==9)a=a.documentElement;return b.toObj(b.removeWhite(a))}
var $pg_namespace={SG_BG_FILE_NAME:"sg_bg.js",SG_STORAGE_FILE_NAME:"sg_sf.html",SITE_TYPE_SEARCH_ENGINE:1,SITE_TYPE_ECOMMERCE:2,SITE_TYPE_TRAVEL:4,SITE_TYPE_CONDUIT_SE:8,DEFAULT_SITE_TYPE:2,IMPR_TYPE_URL_INVESTIGATION:1,IMPR_TYPE_RESULTS_PAGE_LINK:2,IMPR_TYPE_PRODUCT_PAGE:4,IMPR_TYPE_PRODUCT_PAGE_LINK:8,DEFAULT_IMPR_TYPE:5,SERVICE_TYPE_SHOPPING:1,SERVICE_TYPE_COUPONS:2,SERVICE_TYPE_TRAVEL:4,SERVICE_TYPE_COUPONS_HP:8,SERVICE_TYPE_DOD:16,SERVICE_TYPE_HOTELS:32,DEFAULT_SERVICE_TYPE:1,DEFAULT_SERVICE_SUPPORT:32768,
CATALOG_TYPE_WL:2,DEFAULT_CATALOG_TYPE:2,DEFAULT_UPGRADE_INFO:{new_ver:"0.0.0",url:"",span:0,has_new_version:!1},DEFAULT_CLIENT_VERSION:"9.0.16",CLIENT_BUILD:"1",DEFAULT_USER_GROUP:"",DEFAULT_GOOGLE_PATCH:!0,DEFAULT_OFFERS_ANIMATION_TYPE:1,STG_KEY:{SERVER_LOCATION:"pg_server_location",SETTINGS_URL:"pg_settings_url",LAST_SETTINGS_UPDATE:"pg_last_settings_update",FIRST_RUN:"pg_first_run",FIRST_RUN_TIME:"pg_first_run_time",MACHINE_ID:"pg_machine_id",USER_ID:"pg_user_id",SNOOZE_TIME:"pg_snooze_time",
IS_ENABLED:"pg_is_enabled",COUNTRY_CODE:"pg_country_code",LAST_UPGRADE_DISPLAY:"pg_last_upgrade_disp",CATALOG_TYPE:"pg_catalog_type",CATALOG_MODE:"pg_catalog_mode",CX_SERVER_LOCATION:"pg_cx_server",CX_SSL_SERVER_LOCATION:"pg_cx_ssl_server",SETTINGS_UPDATE_INTERVAL:"pg_settings_update_interval",USER_GROUP:"pg_user_group",ACTIVE_SITE_TYPES:"pg_active_site_types",OFFERS_URL:"pg_offers_url",OFFERS_JSON_URL:"pg_offers_json_url",IMPR_TYPE:"pg_impr_type",SERVICE_SUPPORT:"pg_service_support",EXTRA_PARAMS:"pg_extra_params",
UPGRADE_INFO:"pg_upgrade_info",CLIENT_VERSION:"pg_client_ver",WL_CATALOGS_URL:"pg_wl_catalogs_url",WL_CATALOGS_SSL_URL:"pg_wl_catalogs_ssl_url",USER_AGREE:"pg_user_agree",DIST_ID:"pg_dist_id",SUB_DIST_ID:"pg_sub_dist_id",GOOGLE_PATCH:"pg_google_patch",OPT_ENABLE_SEARCH_ENGINES:"pg_enable_search_engines",OPT_ENABLE_ECOMM_SEARCH:"pg_enable_ecomm_search",POST_INSTALL_ACTION:"pg_post_install_action",LAST_POST_DATA:"pg_last_post_data",CLIENT_ACTIONS_ID:"pg_client_actions_id"},SNOOZE_MIN_MINUTES:0,SNOOZE_MAX_MINUTES:2880,
StringFormat:function(){var a=arguments;if(a.length<2)return"";var b=a[0];if(typeof b!="string")return"";return b.replace(/{(\d+)}/g,function(b,d){var e=parseInt(d);if(typeof e!="number")return b;if(typeof a[e+1]!="undefined")return a[e+1];return b})},stringify:function(a,b,c){try{var d=Array.prototype.toJSON;delete Array.prototype.toJSON;var e=JSON.stringify(a,b,c);if(d)Array.prototype.toJSON=d;return e}catch(f){return JSON.stringify(a,b,c)}},normalize_search_term:function(a){a=a.replace(/<([a-z]+)([^<]+)*(?:>(.*)<\/\1>|\s+\/>)/gi,
" ");a=a.replace(/<|>/gi," ");a=a.replace(/\$|R\$|\u00a5|kr|K\u010d|\u0440\u0443\u0431|\u00a3|\u20aa|\u20ac/gi," ");a=a.trim();return $pg_namespace.encodeURIComponent(a)},gen_machine_id:function(){return $pg_namespace.num2hex(Math.random()*4294967295+1,8)+"-"+$pg_namespace.num2hex(Math.random()*4294967295+1,8)+$pg_namespace.num2hex(Math.random()*65535+1,4)},gen_uuid:function(){return $pg_namespace.num2hex(Math.random()*4294967295+1,8)+"-"+$pg_namespace.num2hex(Math.random()*65535+1,4)+"-"+$pg_namespace.num2hex(Math.random()*
65535+1,4)+"-"+$pg_namespace.num2hex(Math.random()*65535+1,4)+"-"+$pg_namespace.num2hex(Math.random()*4294967295+1,8)+$pg_namespace.num2hex(Math.random()*65535+1,4)},pg_date_format:function(a){return a.getUTCDate()+"-"+["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][a.getMonth()]+"-"+a.getUTCFullYear()+" "+a.getUTCHours()+":"+a.getUTCMinutes()+":"+a.getUTCSeconds()},loc_from_url:function(a){var b=document.createElement("a");b.href=a;return b},escape:function(a){return a.replace(/[\\]/g,
"\\\\").replace(/[\"]/g,'\\"').replace(/[']/g,"\\'").replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},unescape:function(a){return a.replace(/\\\\/g,"\\").replace(/\\\"/g,'"').replace(/\\\'/g,"'").replace(/\\n/g,"\n").replace(/\\r/g,"\r")},extend:function(a,b){for(var c in b.prototype)typeof a.prototype[c]=="undefined"&&(a.prototype[c]=b.prototype[c]);return a},kv_pairs_from_str:function(a){for(var b=/([^\/?&]+)={1}([^\/?&]+)|([^\/?&]+):{1}([^\/?&]+)|([^\/?&]+)-{1}([^\/?&]+)/g,c={},d;(d=b.exec(a))!=
null;){for(var e=1,f=d.length;e<f&&d[e]==void 0;)e+=2;e<f-1&&(c[d[e]]=d[e+1])}return c},find_value:function(a,b){var c=a.match(RegExp("(^|[/?&])"+b+"([^/?&]+)","i"));return c?c[2]:null},german_accents:"\u00c4\u00e4\u00d6\u00f6\u00dc\u00fc\u00df\u20ac",french_accents:"\u00c0\u00c2\u00c4\u00c8\u00c9\u00ca\u00cb\u00ce\u00cf\u00d4\u0152\u00d9\u00db\u00dc\u0178\u00e0\u00e2\u00e4\u00e8\u00e9\u00ea\u00eb\u00ee\u00ef\u00f4\u0153\u00f9\u00fb\u00fc\u00ff",italian_accents:"\u00c0\u00c8\u00c9\u00cc\u00d2\u00d3\u00d9\u00e0\u00e8\u00e9\u00ec\u00f2\u00f3\u00f9",
spanish_accents:"\u00c1\u00c9\u00cd\u00d3\u00da\u00d1\u00dc\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1\u00fc",all_accents:"\u00c4\u00e4\u00d6\u00f6\u00dc\u00fc\u00df\u20ac\u00c0\u00c2\u00c8\u00c9\u00ca\u00cb\u00ce\u00cf\u00d4\u0152\u00d9\u00db\u0178\u00e0\u00e2\u00e8\u00e9\u00ea\u00eb\u00ee\u00ef\u00f4\u0153\u00f9\u00fb\u00ff\u00cc\u00d2\u00d3\u00ec\u00f2\u00f3\u00c1\u00cd\u00da\u00d1\u00e1\u00ed\u00fa\u00f1",decode_reg_exp:function(a){var a=a.replace(/\\\]/g,"$hide_it_ti_edih$"),b=a.match(/(\[[^\]]*\[[^\]]*\][^\]]*\])/g);
if(b)for(var c=0,d=b.length;c<d;++c)a=a.replace(b[c],b[c].replace(/\][^$]/,"\\]"));a=a.replace("$hide_it_ti_edih$","\\]");b=$pg_namespace;return a.replace("~G~",b.german_accents).replace("~F~",b.french_accents).replace("~I~",b.italian_accents).replace("~S~",b.spanish_accents).replace("~A~",b.all_accents)},unique:function(a){for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);-1==b.search(RegExp(e))&&(b+=e)}return b},chars2codes:function(a){for(var b="",c=0,d=a.length;c<d;++c)b=b+"\\u"+$pg_namespace.num2hex(a.charCodeAt(c),
4);return b},num2hex:function(a,b){a=Math.round(a);b=Math.round(b);a<0&&(a=4294967295+a+1);for(var c=a.toString(16),b=typeof b=="number"&&b>=0?b:4,d=c.length;d<b;++d)c="0"+c;return c},pack_msg_params:function(){for(var a=Array.prototype.shift.call(arguments),b=[],c=0,d=arguments.length;c<d;++c)b.push(arguments[c]);return{method:a,args:b}},encodeURIComponent:function(a){return encodeURIComponent(a).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A")},
decodeURI:function(a){try{return decodeURI(a)}catch(b){}try{return unescape(a)}catch(c){}return a},encode:function(a){if(typeof a!="string")return a;for(var b="",c=0,d=a.length;c<d;++c){var e=(c+1)%95,f=a.charCodeAt(c);f>=32&&f<=126&&(f=126-(f-32)+e,f=f<=126?f:32+(f-126-1));b+=String.fromCharCode(f)}return b},decode:function(a){if(typeof a!="string")return a;for(var b="",c=0,d=a.length;c<d;++c){var e=(c+1)%95,f=a.charCodeAt(c);f>=32&&f<=126&&(e=f-e,f=127-(e>=32?e-32:95-(32-e))-1);b+=String.fromCharCode(f)}return b}};
$pg_namespace.matcher=function(a,b){this.subject=a;this.rule=b;this.found=!1;this.id=this.value=null;this.logger=$pg_namespace.logger};
$pg_namespace.matcher.prototype={match:function(){this.found=!1;this.value=null},exec:function(){this.match();return this.match_found()},match_found:function(){return this.found},get_value:function(){try{if(!this.match_found())return"";if(typeof this.value=="string"){var a="@name"in this.rule?this.rule["@name"]:"q",b=$pg_namespace.normalize_search_term(this.value);return $pg_namespace.encodeURIComponent(a)+"="+b}var c=[];if(this.value)if(this.rule.fp){var d=this.rule.fp;"#cdata"in d&&(d=d["#cdata"]);
this.value.forEach(function(a){var b="@name"in a.rule?a.rule["@name"]:"q";a.url_value?a=a.url_value:(a=a.get_value(),a=a.replace($pg_namespace.encodeURIComponent(b)+"=",""));d=d.replace("#"+b+"#",a)});c.push(d)}else this.value.forEach(function(a){c.push(a.get_value())});return c.join("&")}catch(e){}return""},set_id:function(a){this.id=a[0];a.shift();this.id_args=a},is_hint:function(){return this.id=="uv"||this.id=="uf"},match_reg_exp:function(a,b){var c=RegExp($pg_namespace.decode_reg_exp(b),"i");
if(c=a.match(c)){this.value=c[c.length-1].trim().toString();if(this.del)this.value=this.value.toLowerCase().replace(this.del,"");this.found=!0}},matcher_from_rule:function(a){if("js"in a)return new $pg_namespace.javascript_matcher(this.subject,a);if(!("@id"in a))return new $pg_namespace.dom_elem_matcher(this.subject,a);var b=a["@id"].split(":");if(b.length==1)return a=new $pg_namespace.dom_elem_matcher(this.subject,a),a.set_id(b),a;var c={cnq:{matcher:$pg_namespace.dom_elem_matcher,id_parts:3},cnc:{matcher:$pg_namespace.dom_elem_matcher,
id_parts:3},idc:{matcher:$pg_namespace.dom_elem_matcher,id_parts:3},"const":{matcher:$pg_namespace.const_matcher,id_parts:2},urex:{matcher:$pg_namespace.page_url_matcher,id_parts:2},trex:{matcher:$pg_namespace.doc_title_matcher,id_parts:2},trmv:{matcher:$pg_namespace.doc_title_matcher,id_parts:2},uvp:{matcher:$pg_namespace.page_url_matcher,id_parts:2},ufp:{matcher:$pg_namespace.page_url_matcher,id_parts:2},uv:{matcher:$pg_namespace.page_url_matcher,id_parts:2},uf:{matcher:$pg_namespace.page_url_matcher,
id_parts:2}},d=b[0];if(d in c)return c=c[d],a=new c.matcher(this.subject,a),b.length>c.id_parts&&(c=b.splice(c.id_parts-1,b.length-c.id_parts+1),b.push(c.join(":"))),a.set_id(b),a;return null}};
$pg_namespace.url_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);this.url=$pg_namespace.decodeURI(a.url).toLowerCase();this.rex_only="@rex_only"in this.rule&&this.rule["@rex_only"]=="1";this.key_part="del"in this.rule?this.rule.del.toLowerCase():null;this.reg_exp=b.reg.toLowerCase();this.reg_exp=this.reg_exp.replace(/([^\\]?)\{/g,"$1(").replace(/([^\\]?)\}/g,"$1)");this.url_value=null;this.url_found=!1};
$pg_namespace.url_matcher.prototype={match:function(){this.value=[];$pg_namespace.matcher.prototype.match.apply(this,arguments);if(!this.rex_only&&this.key_part)this.url_value=$pg_namespace.find_value(this.url,this.key_part),this.url_found=this.url_value!=null;if(!this.url_found&&($pg_namespace.matcher.prototype.match_reg_exp.call(this,this.url,this.reg_exp),this.url_found=this.found,this.url_value=this.value,this.found=!1,this.value=[],this.url_found&&this.key_part))this.url_value=this.url_value.replace(this.key_part,
"");if(this.url_found&&"param"in this.rule){var a=this.rule.param;a.length==void 0&&(a=[a]);this.value=[];for(var b=0,c=a.length;b<c;++b){var d=this.matcher_from_rule(a[b]);if(d.exec())this.value.push(d),this.found=!0}}},match_found:function(){return this.url_found},get_value:function(){try{if(!this.match_found())return"";var a=$pg_namespace.matcher.prototype.get_value.call(this),b="q="+$pg_namespace.normalize_search_term(this.url_value.trim().toString());a.length>0&&(b=b+"&"+a);return b}catch(c){}return""}};
$pg_namespace.extend($pg_namespace.url_matcher,$pg_namespace.matcher);$pg_namespace.dom_elem_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);this.doc=a.doc;this.del="@del"in this.rule?this.rule["@del"].toLowerCase():null};
$pg_namespace.dom_elem_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);var a=this.rule,b=this.get_root_elem();if(b&&("#text"in a&&(b=this.walk(b,a["#text"])),b&&!("@tag"in a&&a["@tag"].length>0&&b.tagName.toLowerCase()!=a["@tag"].toLowerCase()))){if("@attribute"in a&&a["@attribute"].length>0){var c=a["@attribute"],d=a["@value"],a=RegExp("@type"in a&&a["@type"].toLowerCase()=="contain"?d:"^"+d+"$","i"),d=b.getAttribute(c);if(!d||d==null)return;this.del&&
(d=d.toLowerCase().replace(this.del,""));if(!d.match(a))return}else if("@value"in a&&a["@value"].length>0&&(c=b.innerText||b.textContent,this.del&&(c=c.toLowerCase().replace(this.del,"")),d=a["@value"],a=RegExp("@type"in a&&a["@type"].toLowerCase()=="contain"?d:"^"+d+"$","i"),!c.match(a)))return;this.found=!0;this.value=b}},get_root_elem:function(){if(!("@id"in this.rule))return this.doc;if(this.id_args.length==0)return this.doc.getElementById(this.id);for(var a=this.id,b=this.id_args[1],c=this.doc.getElementsByTagName(this.id_args[0]),
d=a=="cnq"||a=="cnc"?"class":"id",a=RegExp(a=="idc"||a=="cnc"?b:"^"+b+"$"),e=0,f=c.length;e<f;++e){var h=c[e],b=h.getAttribute(d);if(!b&&d=="class")b=h.className;if(b&&b.match(a))return h}return null},walk_map:{c:"firstChild",s:"nextSibling",r:"previousSibling",p:"parentNode",l:"lastChild"},walk:function(a,b){if(!a||b.length==0)return a;var c=b.charAt(0),d=this.walk_map[c.toLowerCase()];if((a=a[d])&&c.toLowerCase()==c){c=this.walk_map[d=="nextSibling"||d=="firstChild"?"s":"r"];for(d=a;a&&(a.nodeType==
Node.TEXT_NODE||a.nodeType==Node.COMMENT_NODE);)(a=a[c])&&(d=a);a=d}return this.walk(a,b.substr(1))},get_value:function(){if(this.match_found()){var a=this.value.innerText||this.value.textContent||this.value.nodeValue;if(a&&(this.value=a.trim().toString(),this.del))this.value=this.value.toLowerCase().replace(this.del,"")}return $pg_namespace.matcher.prototype.get_value.call(this)}};$pg_namespace.extend($pg_namespace.dom_elem_matcher,$pg_namespace.matcher);
$pg_namespace.const_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b)};$pg_namespace.const_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);this.value=this.rule["@id"].split(":")[1];this.found=!0}};$pg_namespace.extend($pg_namespace.const_matcher,$pg_namespace.matcher);$pg_namespace.javascript_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);if("#cdata"in b.js)b.js=b.js["#cdata"]};
$pg_namespace.javascript_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);try{this.found=this.value=eval("var document = this.subject.doc; function pgFoo() {"+this.rule.js+"}; this.value = pgFoo();")}catch(a){this.found=!1}}};$pg_namespace.extend($pg_namespace.javascript_matcher,$pg_namespace.matcher);
$pg_namespace.page_url_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);this.url=$pg_namespace.decodeURI(a.url).toLowerCase();this.del="@del"in this.rule?this.rule["@del"].toLowerCase():null;this.url_value=null;this.url_found=!1};
$pg_namespace.page_url_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);var a="match_"+this.id;if(a in this)this[a](this.id_args[0])},match_urex:function(a){$pg_namespace.matcher.prototype.match_reg_exp.call(this,this.url,a);this.url_found=this.found;this.url_value=this.value;this.found=!1;this.value=[];if(this.match_found()&&"@value"in this.rule){var a=this.rule["@value"].toLowerCase(),b="@type"in this.rule&&this.rule["@type"].toLowerCase()=="equal"?
"equal":"contain";this.url_value=this.url_value.toLowerCase();if(this.del)this.url_value=this.url_value.toLowerCase().replace(this.del,"");if(b=="equal"&&this.url_value!=a||b=="contain"&&this.url_value.indexOf(a)==-1)this.url_value=null,this.url_found=!1}},match_uvp:function(a){var b=$pg_namespace.kv_pairs_from_str(this.url),a=a.toLowerCase(),c;for(c in b)if(c==a){this.url_value=b[c].trim().toString();if(this.del)this.url_value=this.url_value.toLowerCase().replace(this.del,"");this.url_found=!0;break}},
match_ufp:function(a){var b=this.subject.doc.location.pathname;b.charAt(0)=="/"&&(b=b.substring(1));b=b.split("/");if(b.length>=a){this.url_value=b[a-1].trim().toString();if(this.del)this.url_value=this.url_value.toLowerCase().replace(this.del,"");this.url_found=!0}},match_uv:function(a){this.match_uvp(a)},match_uf:function(a){this.match_ufp(a)},match_found:function(){return this.url_found},get_value:function(){if(!this.match_found())return"";var a=$pg_namespace.matcher.prototype.get_value.call(this),
b=$pg_namespace.encodeURIComponent("@name"in this.rule?this.rule["@name"]:"q")+"="+this.url_value.trim().toString();a.length>0&&(b=b+"&"+a);return b}};$pg_namespace.extend($pg_namespace.page_url_matcher,$pg_namespace.matcher);$pg_namespace.doc_title_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);this.title=a.title;this.del="@del"in this.rule?this.rule["@del"].toLowerCase():null};
$pg_namespace.doc_title_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);var a="match_"+this.id;if(a in this)this[a](this.id_args[0])},match_trex:function(a){$pg_namespace.matcher.prototype.match_reg_exp.call(this,this.title,a)},match_trmv:function(a){var b=this.title.toLowerCase();a.toLowerCase().split(";").forEach(function(a){b=b.replace(RegExp(a,"gi"),"")});if(b.length)this.value=b.trim().toString(),this.del&&(attribute=attribute.toLowerCase().replace(this.del,
"")),this.found=!0}};$pg_namespace.extend($pg_namespace.doc_title_matcher,$pg_namespace.matcher);$pg_namespace.product_matcher=function(a,b){$pg_namespace.matcher.call(this,a,b);this.service_type="@service"in b?b["@service"]:$pg_namespace.DEFAULT_SERVICE_TYPE};
$pg_namespace.product_matcher.prototype={match:function(){$pg_namespace.matcher.prototype.match.apply(this,arguments);if("match"in this.rule){var a=this.rule.match;a.length==void 0&&(a=[a]);for(var b=0,c=a.length;b<c;++b){var d=a[b],d=this.matcher_from_rule(d);if(!d.exec())return}}if("param"in this.rule){a=this.rule.param;a.length==void 0&&(a=[a]);this.value=[];b=0;for(c=a.length;b<c;++b)if(d=a[b],d=this.matcher_from_rule(d),d.exec())this.value.push(d),this.found=this.found||!d.is_hint()}},get_value:function(){var a=
$pg_namespace.matcher.prototype.get_value.call(this);if(a.length==0)return a;if("param"in this.rule&&this.rule.fp){var b=this.rule.param;b.length==void 0&&(b=[b]);for(var c=0,d=b.length;c<d;++c)var e=b[c],a=a.replace("#"+("@name"in e?e["@name"]:"q")+"#","")}if(this.service_type==$pg_namespace.SERVICE_TYPE_COUPONS||this.service_type==$pg_namespace.SERVICE_TYPE_COUPONS_HP)b=window.location.host,c=b.indexOf(":"),c!=-1&&(b=b.substring(0,c)),a=[a,"hn="+b].join("&");return[a,"service="+this.service_type].join("&")}};
$pg_namespace.extend($pg_namespace.product_matcher,$pg_namespace.matcher);
$pg_namespace.site_matcher=function(a,b,c){var d={};a?(d.doc=a,d.url=a.location.href,d.title=a.title):(d.doc=null,d.url=b,d.title="");$pg_namespace.matcher.call(this,d,c);this.site_id="@id"in c?c["@id"]:"";this.site_type="@type"in c?parseInt(c["@type"]):$pg_namespace.DEFAULT_SITE_TYPE;this.excludedServiceTypes=null;if(pg_settings.EXCLUDED_SERVICE_TYPES.length>0){this.excludedServiceTypes=pg_settings.EXCLUDED_SERVICE_TYPES.split(",");for(a=0;a<this.excludedServiceTypes.length;a++)this.excludedServiceTypes[a]=
parseInt(this.excludedServiceTypes[a])}};
$pg_namespace.site_matcher.prototype={match:function(){try{$pg_namespace.matcher.prototype.match.apply(this,arguments);this.value=[];var a=this.rule;if(!this.subject.doc&&"url"in a){if(a.url.length==void 0)a.url=[a.url];for(var b=0,c=a.url.length;b<c;++b){var d=new $pg_namespace.url_matcher(this.subject,a.url[b]);if(!(this.excludedServiceTypes&&this.excludedServiceTypes.length>0&&this.excludedServiceTypes.indexOf(d.site_type==$pg_namespace.SITE_TYPE_TRAVEL?$pg_namespace.SERVICE_TYPE_HOTELS:$pg_namespace.SERVICE_TYPE_SHOPPING)!=
-1)&&d.exec()){this.value.push(d);this.found=!0;return}}}var e=pg_instance.get_service_support();if(this.subject.doc&&!this.match_found()&&this.subject.doc&&"product"in a){if(a.product.length==void 0)a.product=[a.product];b=0;for(c=a.product.length;b<c;++b){var d=new $pg_namespace.product_matcher(this.subject,a.product[b]),f=parseInt(d.service_type);if(!(this.excludedServiceTypes&&this.excludedServiceTypes.length>0&&this.excludedServiceTypes.indexOf(f)!=-1)&&(f&e)!=0&&d.exec()){this.value.push(d);
this.found=!0;break}}}}catch(h){}},get_value:function(){try{var a=$pg_namespace.matcher.prototype.get_value.call(this);if(a.length==0)return a}catch(b){}return[a,"site_num="+this.site_id,"st="+this.site_type].join("&")}};$pg_namespace.extend($pg_namespace.site_matcher,$pg_namespace.matcher);
$pg_namespace.page_handler=function(a){this.logger=$pg_namespace.logger;this.doc=a;addListener(window,"message",function(a){return function(c){a.on_window_msg(c)}}(this),!1);this.reparse={is_on:!1,timer:0,delay:2E3,last_search:"",cur_search:"",last_result_params:""};this.post_hook();this.skip_first_load=this.g_hooked=!1;this.last_offers_url="";this.valid_request=!1;this.XSLTSliderPosition=pg_settings.DEFAULT_SLIDER_POS};
$pg_namespace.page_handler.prototype={OFFERS_FRAME_ID:"comparison_shopping_offers_iframe_id",OFFERS_FRAME_WIDTH:1,OFFERS_FRAME_HEIGHT:1,OFFERS_FRAME_HEIGHT_RATE:10,OFFERS_FRAME_HEIGHT_STEP:2,ebay_hook:function(a){try{if(a){var b="@id"in a?a["@id"]:"";if(b=="1707"&&document.URL=="http://www.ebay.com/")for(var c=this,d=document.getElementsByClassName("feed item loaded"),e=0;e<d.length;e++)addListener(d[e],"click",function(d){try{var e=d.currentTarget.getElementsByClassName("description");if(e&&!(e.length<
1)){var f=e[0].getElementsByTagName("a");if(f&&!(f.length<1)&&c.is_active_impr_type(a,$pg_namespace.IMPR_TYPE_PRODUCT_PAGE)){var n="@type"in a?parseInt(a["@type"]):$pg_namespace.DEFAULT_SITE_TYPE,p=["q="+$pg_namespace.normalize_search_term(f[0].innerText||f[0].textContent),"site_num="+b,"st="+n,"trig="+$pg_namespace.IMPR_TYPE_PRODUCT_PAGE,"impr="+pg_instance.get_impr_type()].join("&"),j=pg_instance.make_offers_url(p);if(j!=c.last_offers_url)c.get_offers(j),c.last_offers_url=j}}}catch(r){}})}}catch(f){}},
amazon_hook:function(a){try{if(a){var b="@id"in a?a["@id"]:"";if(b=="10"){var c=this,d=document.getElementById("nav-searchbar");d&&addListener(d,"submit",function(){try{var d=document.getElementById("twotabsearchtextbox");if(d&&c.is_active_impr_type(a,$pg_namespace.IMPR_TYPE_URL_INVESTIGATION)){var e="@type"in a?parseInt(a["@type"]):$pg_namespace.DEFAULT_SITE_TYPE,g=["q="+$pg_namespace.normalize_search_term(d.value),"site_num="+b,"st="+e,"trig="+$pg_namespace.IMPR_TYPE_URL_INVESTIGATION,"impr="+pg_instance.get_impr_type()].join("&"),
l=pg_instance.make_offers_url(g);if(l!=c.last_offers_url)c.get_offers(l),c.last_offers_url=l}}catch(n){}})}}}catch(e){}},showOfferFromRule:function(a,b){try{var c=$pg_namespace.loc_from_url(document.URL).host,d=c.indexOf(":");d!=-1&&(c=c.substring(0,d));var e=pg_wl_catalogger.get_rule(c);if(e){var f="@id"in e?e["@id"]:"",h="@type"in e?parseInt(e["@type"]):$pg_namespace.DEFAULT_SITE_TYPE,g=["q="+$pg_namespace.normalize_search_term(a),"site_num="+f,"st="+h,"trig="+b?b:$pg_namespace.IMPR_TYPE_PRODUCT_PAGE,
"impr="+pg_instance.get_impr_type()].join("&"),l=pg_instance.make_offers_url(g);if(l!=this.last_offers_url)this.get_offers(l),this.last_offers_url=l}}catch(n){}},showCouponsFromRule:function(a){try{var b=$pg_namespace.loc_from_url(document.URL).host,c=b.indexOf(":");c!=-1&&(b=b.substring(0,c));var d=pg_wl_catalogger.get_rule(b);if(d){var e="@id"in d?d["@id"]:"",f="@type"in d?parseInt(d["@type"]):$pg_namespace.DEFAULT_SITE_TYPE,h=[a,"service="+$pg_namespace.SERVICE_TYPE_COUPONS_HP,"site_num="+e,"st="+
f,"trig="+$pg_namespace.IMPR_TYPE_PRODUCT_PAGE,"impr="+pg_instance.get_impr_type()].join("&"),g=pg_instance.make_offers_url(h);if(g!=this.last_offers_url)this.get_offers(g),this.last_offers_url=g}}catch(l){}},is_google_patch_enabled:function(){return typeof pg_instance.get_google_patch()!="undefined"&&pg_instance.get_google_patch()},g_hook:function(){if(!this.g_hooked){var a=this.doc.getElementById("gbqfq")||this.doc.getElementById("lst-ib");if(a)this.reparse.last_search=a.value,$this=this,addListener(a,
"keyup",function(){if($this.reparse.cur_search!=a.value&&($this.reparse.cur_search=a.value,$this.reparse.timer&&window.clearTimeout($this.reparse.timer),$this.reparse.cur_search!=$this.reparse.last_search))$this.reparse.timer=window.setTimeout(function(){$this.reparse.timer=0;$this.reparse.is_on=!0;$this.page_investigate();$this.reparse.last_search=$this.reparse.cur_search},$this.reparse.delay)},!0);this.g_hooked=!0}},g_unhook:function(){var a=this.doc.getElementById("lst-ib");a&&a.removeEventListener("keyup",
this,!0);this.g_hooked=!1},post_hook:function(){var a=document.forms;if(a)for(var b=this,c=0,d=a.length;c<d;++c){var e=a[c];e.method=="post"&&addListener(e,"submit",function(a){try{var c=a.currentTarget,a={};if(typeof document.evaluate=="undefined"||typeof XPathResult=="undefined")for(var d=c.querySelectorAll("input[type='text']"),e=0,n=d.length;e<n;++e){var p=d[e];a[p.name]=p.value}else{d=document.evaluate(".//input[@type='text']",c,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);e=0;for(n=d.snapshotLength;e<
n;++e)p=d.snapshotItem(e),a[p.name]=p.value}pg_instance.set_last_post_data($pg_namespace.stringify({args:a,host:b.location.host,time:(new Date).valueOf()}))}catch(j){}},!1)}},offers_set_position:function(a){this.XSLTSliderPosition=a},display_offers:function(){var a=this.doc.getElementById(this.OFFERS_FRAME_ID);if(a)if(this.OFFERS_FRAME_HEIGHT==0)a.setAttribute("height",0),a.style.height=0,a.setAttribute("width",0),a.style.width=0;else{var b,c,d,e,f,h,g;this.XSLTSliderPosition=="tr"?(c=pg_settings.SLIDER_OFFSET+
this.OFFERS_FRAME_HEIGHT>document.documentElement.clientHeight?document.documentElement.clientHeight-this.OFFERS_FRAME_HEIGHT+"px !important;":pg_settings.SLIDER_OFFSET+"px !important;",d="auto",b="0px",e="height",f=this.OFFERS_FRAME_HEIGHT+"px !important;",h="width",g=this.OFFERS_FRAME_WIDTH+this.getScrollbarsWidth()):this.XSLTSliderPosition=="bc"?(c="auto",d="0px",b=pg_settings.SLIDER_OFFSET+this.OFFERS_FRAME_WIDTH>document.documentElement.clientWidth?document.documentElement.clientWidth-this.OFFERS_FRAME_WIDTH+
"px !important;":pg_settings.SLIDER_OFFSET+"px !important;",e="width",f=this.OFFERS_FRAME_WIDTH+this.getScrollbarsWidth()+"px !important;",h="height",g=this.OFFERS_FRAME_HEIGHT):(c="auto",b=d="0px",pg_settings.offers_animation_type==2?(e="height",f=this.OFFERS_FRAME_HEIGHT+"px !important;",h="width",g=this.OFFERS_FRAME_WIDTH+this.getScrollbarsWidth()):(e="width",f=this.OFFERS_FRAME_WIDTH+this.getScrollbarsWidth()+"px !important;",h="height",g=this.OFFERS_FRAME_HEIGHT));b=$pg_namespace.StringFormat("display:block;position:fixed;top:{0};bottom:{1};right:{2};{3}:{4};border:none;margin:0;padding:0;z-index:2147483647;",
c,d,b,e,f);a.style.cssText=b;var l=window.setInterval(function(a,b,c,d){return function(){var e=parseInt(a.getAttribute(b)),f=e<c?1:e>c?-1:0;if(f!=0){var h=e+d*f;f<0&&h<c?h=c:f>0&&h>c&&(h=c);a.setAttribute(b,h);if(h!=c)return}try{if(getComputedStyle&&jQuery){var g=getComputedStyle(a),e=parseInt(g[b]);e!=c&&jQuery(a).css(b,h)}}catch(m){}clearInterval(l)}}(a,h,g,this.OFFERS_FRAME_HEIGHT_STEP),this.OFFERS_FRAME_HEIGHT_RATE)}},offers_iframe_set_size:function(a,b){this.OFFERS_FRAME_WIDTH=parseInt(a);this.OFFERS_FRAME_HEIGHT=
parseInt(b);this.display_offers()},offers_iframe_hide:function(){var a=this.doc.getElementById(this.OFFERS_FRAME_ID);a&&this.offers_iframe_set_size(a.getAttribute("width"),0)},offers_open_url:function(){},offers_open_WhatsThis:function(){conduit.valueApps.openWhatsThis(pg_settings.MAM_APP_ID)},isQuirksMode:function(){if(pg_settings.BROWSER_TYPE!="ie")return!1;if(document.documentMode){if(document.documentMode==5)return!0}else if(document.compatMode!=="CSS1Compat")return!0;return!1},getScrollbarsWidth:function(){try{if(pg_settings.BROWSER_TYPE!=
"ie")return 0;if(!getComputedStyle)return 0;var a=document.getElementsByTagName("html")[0];if(getComputedStyle(a)["-ms-overflow-style"]=="-ms-autohiding-scrollbar")return 15}catch(b){}return 0},get_offers:function(a){if(pg_settings.MAM_SHOW_UI==!0)return this.get_offers_json(a);this.valid_request=a.indexOf("q=")!=-1;if(this.valid_request!=!1){var b=this.doc.getElementById(this.OFFERS_FRAME_ID);if(b)b.setAttribute("height",0),b.setAttribute("src",a);else{this.offers_iframe_origin=$pg_namespace.loc_from_url(a).hostname;
b=this.doc.createElement("iframe");b.setAttribute("id",this.OFFERS_FRAME_ID);if(typeof b.frameBorder!=="undefined")b.frameBorder="0";b.setAttribute("width",this.OFFERS_FRAME_WIDTH);b.setAttribute("height",this.OFFERS_FRAME_HEIGHT);b.setAttribute("scrolling","no");b.setAttribute("src",a);this.doc.body.appendChild(b)}}},get_offers_json:function(a){function b(){if(typeof c.readyState=="undefined"||c.readyState==4)try{if(typeof c.status=="undefined"||c.status==200){var a=JSON.parse(c.responseText);conduit.valueApps.showOffer(a,
pg_settings.MAM_APP_ID)}}catch(b){}}var c=new XMLHttpRequest;try{c.responseType===void 0&&typeof XDomainRequest!=="undefined"?(c=new XDomainRequest,c.onload=b,c.ontimeout=function(){},c.onprogress=function(){},c.timeout=9E3):c.onreadystatechange=b,c.onerror=function(){},c.open("GET",a,!0),c.send()}catch(d){}},on_prefs_changed:function(a){var b=parseInt(a[$pg_namespace.STG_KEY.SNOOZE_TIME]),a=a[$pg_namespace.STG_KEY.IS_ENABLED]?!0:!1;this.doc.getElementById(this.OFFERS_FRAME_ID)&&(!a||b>(new Date).valueOf())&&
this.offers_iframe_hide()},offers_iframe_set_snooze:function(a){a=parseInt(a);a=Math.min($pg_namespace.SNOOZE_MAX_MINUTES,Math.max($pg_namespace.SNOOZE_MIN_MINUTES,a));pg_instance.set_snooze_time(a*6E4)},hide_offers:function(){this.offers_iframe_hide()},on_window_msg:function(a){if(a.origin.indexOf(this.offers_iframe_origin)!=-1)try{var b=JSON.parse(a.data);this[b.method]&&this[b.method].apply(this,b.args)}catch(c){}},set_skip_first_load:function(){this.skip_first_load=!0},get_last_post_data:function(a){var b=
"",c=pg_instance.get_last_post_data();if(c!==""){var c=JSON.parse(c),d=(new Date).valueOf();if(this.location.host==c.host&&d-c.time<3E5){b=[];for(k in c.args)b.push(k+"="+$pg_namespace.encodeURIComponent(c.args[k]));b=b.join("&");a&&pg_instance.set_last_post_data("")}}return b},page_investigate:function(){try{var a=document.URL;this.location=$pg_namespace.loc_from_url(a);var b=this.get_last_post_data(!0);b.length&&(a=a.indexOf("?")==-1?a+"?"+b:a+"&"+b);this.url=a;var c=this.location.host,d=c.indexOf(":");
d!=-1&&(c=c.substring(0,d));if(this.skip_first_load)var e=pg_wl_catalogger.get_rule(c);else if(pg_instance.should_display_upgrade_notification())this.upgrade_info_url=pg_instance.get_upgrade_info().url,pg_instance.set_last_upgrade_display(0),this.get_offers(this.upgrade_info_url),pg_instance.set_last_upgrade_display(Date.now());else if(e=pg_wl_catalogger.get_rule(c))if(e.site_type="@type"in e?parseInt(e["@type"]):$pg_namespace.DEFAULT_SITE_TYPE,e.impr_types="@impr_type"in e?parseInt(e["@impr_type"]):
$pg_namespace.DEFAULT_IMPR_TYPE,this.is_active_site_type(e)&&pg_instance.get_user_agree()&&!this.run_url_investigator(e)){var f="@doc_complete_delay"in e?parseInt(e["@doc_complete_delay"]):0;pg_settings.FALLBACK_URL.length>0&&(f=0);f>0?setTimeout(function(a){return function(){a.run_product_investigator(e)}}(this),f):this.run_product_investigator(e)}}catch(h){}},run_url_investigator:function(a){if(this.is_active_impr_type(a,$pg_namespace.IMPR_TYPE_URL_INVESTIGATION)&&(a=new $pg_namespace.site_matcher(null,
this.url,a),a.exec())){a=a.get_value();a+="&trig="+$pg_namespace.IMPR_TYPE_URL_INVESTIGATION;a+="&impr="+pg_instance.get_impr_type();a=pg_instance.make_offers_url(a);if(a!=this.last_offers_url)this.get_offers(a),this.last_offers_url=a;return!0}return!1},run_product_investigator:function(a){if(this.is_active_impr_type(a,$pg_namespace.IMPR_TYPE_PRODUCT_PAGE)){var b=new $pg_namespace.site_matcher(this.doc,null,a);if(b.exec()&&(b=b.get_value(),!this.reparse.is_on||this.reparse.last_result_params!=b))if(this.reparse.last_result_params=
b,b+="&trig="+$pg_namespace.IMPR_TYPE_PRODUCT_PAGE,b+="&impr="+pg_instance.get_impr_type(),b=pg_instance.make_offers_url(b),b!=this.last_offers_url)this.get_offers(b),this.last_offers_url=b;this.is_google_patch_enabled()&&a["@name"].indexOf("google")==0&&this.g_hook()}},is_active_site_type:function(a){return(a.site_type&pg_instance.get_effective_active_site_types())!=0},is_active_impr_type:function(a,b){return(b&a.impr_types&pg_instance.get_effective_impr_type())!=0}};
var pg_conf_class=function(){var a,b=function(b){if(typeof b!="string")return b;if(pg_settings.BROWSER_VERSION.toString().startsWith("8"))return b;var c="",d=b.length;for(i=0;i<d;++i)c+=String.fromCharCode(a^b.charCodeAt(i));return c},c=function(b){if(typeof b!="string")return b;if(pg_settings.BROWSER_VERSION.toString().startsWith("8"))return b;var c="",d=b.length;for(i=0;i<d;i++)c+=String.fromCharCode(a^b.charCodeAt(i));return c},d=function(a,b,c,d){this.storage=d;this.set=a;this.get=b;this.del=
c;this.master_key="sg_conf_global_new";this.cache={};this.standalone=!1;this.storageFrame=this.on_get_item_results_callback=this.refresh_cache_results_callback=null;this.STORAGE_FRAME_ID="comparison_shopping_sf_id";this.STORAGE_FRAME_STYLE="position:fixed;right:0;bottom:0;border:none;margin:0;padding:0;z-index:2147483647;display:none"};d.prototype={init:function(a,b,c){var d="http:";b==!0&&(d="https:");this.storage_url=d+pg_settings.PG_BASE_URL+$pg_namespace.SG_STORAGE_FILE_NAME;if(this.standalone=
a){var l=this;addListener(window,"message",function(a){if(a.origin==l.storage_iframe_origin){var b=JSON.parse(a.data);if(b.method=="on_storage_ready")$pg_namespace.BrowserDetect.isIE()||l.storage_call("register_storage_change"),l.storage_call("getItem",l.master_key);else if(b.method=="on_get_item_results")if(a=b.args[0],b=b.args[1],a==l.master_key)a=l.refresh_success(c),a(b);else{if(l.on_get_item_results_callback)l.on_get_item_results(l.on_get_item_results_callback)(b),l.on_get_item_results_callback=
null}else b.method=="on_refresh_cache_results"?(b=b.args[1],a=l.refresh_success(null),a(b),l.refresh_cache_results_callback&&l.refresh_cache_results_callback()):b.method=="on_storage_changed"&&(a=b.args[0],b=b.args[1],a==l.master_key&&(a=l.refresh_success(null),a(b),pg_settings_manager.reschedule()))}},!1);this.createStorageFrame()}else conduit.valueApps.storage.getKey(this.master_key,this.refresh_success(c),this.refresh_failure(c))},createStorageFrame:function(){this.storageFrame=document.getElementById(this.STORAGE_FRAME_ID);
if(!this.storageFrame){var a=$pg_namespace.loc_from_url(this.storage_url),b=a.host,c=b.indexOf(":");c!=-1&&(b=b.substring(0,c));this.storage_iframe_origin=a.protocol+"//"+b;this.storageFrame=document.createElement("iframe");this.storageFrame.setAttribute("id",this.STORAGE_FRAME_ID);this.storageFrame.style.cssText=this.STORAGE_FRAME_STYLE;this.storageFrame.setAttribute("width",0);this.storageFrame.setAttribute("height",0);this.storageFrame.setAttribute("src",this.storage_url);document.body.appendChild(this.storageFrame)}},
storage_call:function(){for(var a=Array.prototype.shift.call(arguments),b=[],c=0,d=arguments.length;c<d;++c)b.push(arguments[c]);this.storageFrame.contentWindow.postMessage($pg_namespace.stringify({method:a,args:b}),this.storage_url)},commit:function(){try{var a=b($pg_namespace.stringify(this.cache));this.standalone?this.storage_call("setItem",this.master_key,a,$pg_namespace.BrowserDetect.isIE()):($this=this,this.storage.set(this.master_key,a,function(){},function(){}))}catch(c){return!1}return!0},
refresh_cache:function(a){this.refresh_cache_results_callback=a;this.storage_call("refresh_cache",this.master_key)},refresh_success:function(a){var b=this;return function(d){try{if(d&&d!="")b.cache=JSON.parse(c(d))}catch(g){b.storage_call("removeItem",b.master_key);return}a!=null&&a()}},on_get_item_results:function(a){return function(b){try{b&&b!=""&&(b=JSON.parse(c(b)))}catch(d){b=null}a!=null&&a(b)}},refresh_failure:function(a){return function(){a()}},set_str:function(a,b,c){this.set(a,b,c)},get_str:function(a,
b){var c=this.get(a);if(c==null||typeof c=="undefined")c=b;return c},set_int:function(a,b,c){this.set(a,b,c)},get_int:function(a,b){var c=this.get(a);if(c==null||typeof c=="undefined")c=b;return parseInt(c)},set_bool:function(a,b,c){this.set(a,b,c)},get_bool:function(a,b){var c=this.get(a);if(c==null||typeof c=="undefined")return b;return c=="true"||c==!0},set_obj:function(a,b,c){try{this.set_str(a,$pg_namespace.stringify(b),c)}catch(d){}},get_obj:function(a,b){var c=this.get(a);if(c==null||typeof c==
"undefined")return b;try{return JSON.parse(c)}catch(d){}return b},setNoCache:function(a,c){try{var d=b($pg_namespace.stringify(c));this.storage_call("setItem",a,d)}catch(g){}},getNoCache:function(a,b){this.on_get_item_results_callback=b;this.storage_call("getItem",a)}};return{init:function(b,c,d,g){a=d;this.global.init(b,c,g)},global:new d(function(a,b,c){this.cache[a]=b;c||this.commit()},function(a){if(a in this.cache)return this.cache[a];return null},function(a,b){delete this.cache[a];b||this.commit()},
localStorage)}},pg_instance_class=function(){var a=$pg_namespace;return{set_enabled:function(b){pg_conf.global.set_bool(a.STG_KEY.IS_ENABLED,b.toString());b&&this.set_snooze_time(0)},is_enabled:function(){return pg_conf.global.get_bool(a.STG_KEY.IS_ENABLED,!0)},is_first_run:function(){return pg_conf.global.get_bool(a.STG_KEY.FIRST_RUN,!0)},set_first_run:function(b,c){pg_conf.global.set_bool(a.STG_KEY.FIRST_RUN,b,c);if(b){var d=$pg_namespace.pg_date_format(new Date);pg_conf.global.set_str(a.STG_KEY.FIRST_RUN_TIME,
d,c)}},reset_first_run:function(){for(key in a.STG_KEY)pg_conf.global.del(a.STG_KEY[key])},get_first_run_time:function(){this.is_first_run();return pg_conf.global.get_str(a.STG_KEY.FIRST_RUN_TIME,"")},set_first_run_time:function(b,c){pg_conf.global.set_str(a.STG_KEY.FIRST_RUN_TIME,b,c)},get_user_agree:function(){return!0},set_user_agree:function(b){pg_conf.global.set_bool(a.STG_KEY.USER_AGREE,b)},get_post_install_action:function(){return pg_conf.global.get_bool(a.STG_KEY.POST_INSTALL_ACTION,!0)},
set_post_install_action:function(b){pg_conf.global.set_bool(a.STG_KEY.POST_INSTALL_ACTION,b)},is_agreement_set:function(){return!0},get_machine_id:function(){var b=pg_conf.global.get_str(a.STG_KEY.MACHINE_ID,"");b.length==0&&(b=$pg_namespace.gen_machine_id(),pg_conf.global.set_str(a.STG_KEY.MACHINE_ID,b));return b},get_user_id:function(){var b=pg_conf.global.get_str(a.STG_KEY.USER_ID,"");b.length==0&&(b=$pg_namespace.gen_uuid(),pg_conf.global.set_str(a.STG_KEY.USER_ID,b));return b},get_dist_id:function(){return pg_settings.DISTRIBUTER_ID},
get_sub_dist_id:function(){return pg_settings.SUB_DISTRIBUTER_ID},is_snoozing:function(){return this.get_snooze_time()>(new Date).valueOf()},set_snooze_time:function(b){pg_conf.global.set_int(a.STG_KEY.SNOOZE_TIME,(new Date).valueOf()+b)},get_snooze_time:function(){return pg_conf.global.get_int(a.STG_KEY.SNOOZE_TIME,0)},platform_info:function(){},set_country_code:function(b){pg_conf.global.set_str(a.STG_KEY.COUNTRY_CODE,b)},get_country_code:function(){return pg_conf.global.get_str(a.STG_KEY.COUNTRY_CODE,
"")},set_last_settings_update:function(b,c){pg_conf.global.set_int(a.STG_KEY.LAST_SETTINGS_UPDATE,b,c)},get_last_settings_update:function(){return pg_conf.global.get_int(a.STG_KEY.LAST_SETTINGS_UPDATE,0)},set_settings_update_interval:function(b,c){pg_conf.global.set_int(a.STG_KEY.SETTINGS_UPDATE_INTERVAL,b,c)},get_settings_update_interval:function(){return pg_conf.global.get_int(a.STG_KEY.SETTINGS_UPDATE_INTERVAL,pg_settings.DEFAULT_SETTINGS_FILE_UPDATE_INTERVAL)},set_catalog_type:function(b,c){if(b!=
a.CATALOG_TYPE_WL)b=a.DEFAULT_CATALOG_TYPE;pg_conf.global.set_int(a.STG_KEY.CATALOG_TYPE,b,c)},get_catalog_type:function(){return pg_conf.global.get_int(a.STG_KEY.CATALOG_TYPE,a.DEFAULT_CATALOG_TYPE)},is_active:function(){return this.is_enabled()&&this.get_user_agree()&&!this.is_snoozing()},set_wl_catalogs_url:function(b,c){pg_conf.global.set_str(a.STG_KEY.WL_CATALOGS_URL,b,c)},get_wl_catalogs_url:function(){return pg_conf.global.get_str(a.STG_KEY.WL_CATALOGS_URL,"")},set_wl_catalogs_ssl_url:function(b,
c){pg_conf.global.set_str(a.STG_KEY.WL_CATALOGS_SSL_URL,b,c)},get_wl_catalogs_ssl_url:function(){return pg_conf.global.get_str(a.STG_KEY.WL_CATALOGS_SSL_URL,"")},set_cx_server_location:function(b,c){pg_conf.global.set_str(a.STG_KEY.CX_SERVER_LOCATION,b,c)},get_cx_server_location:function(){return pg_conf.global.get_str(a.STG_KEY.CX_SERVER_LOCATION,"")},set_cx_ssl_server_location:function(b,c){pg_conf.global.set_str(a.STG_KEY.CX_SSL_SERVER_LOCATION,b,c)},get_cx_ssl_server_location:function(){return pg_conf.global.get_str(a.STG_KEY.CX_SSL_SERVER_LOCATION,
"")},set_offers_url:function(b,c){pg_conf.global.set_str(a.STG_KEY.OFFERS_URL,b,c)},get_offers_url:function(){return pg_conf.global.get_str(a.STG_KEY.OFFERS_URL,pg_settings.DEFAULT_OFFERS_URL)},set_offers_json_url:function(b,c){pg_conf.global.set_str(a.STG_KEY.OFFERS_JSON_URL,b,c)},get_offers_json_url:function(){return pg_conf.global.get_str(a.STG_KEY.OFFERS_JSON_URL,pg_settings.DEFAULT_OFFERS_JSON_URL)},set_user_group:function(b,c){pg_conf.global.set_str(a.STG_KEY.USER_GROUP,b,c)},get_user_group:function(){return pg_conf.global.get_str(a.STG_KEY.USER_GROUP,
a.DEFAULT_USER_GROUP)},set_active_site_types:function(b,c){pg_conf.global.set_int(a.STG_KEY.ACTIVE_SITE_TYPES,b,c)},get_active_site_types:function(){return pg_conf.global.get_int(a.STG_KEY.ACTIVE_SITE_TYPES,pg_settings.DEFAULT_ACTIVE_SITE_TYPES)},get_effective_active_site_types:function(){var a=this.get_active_site_types();this.get_search_engine_enabled()||(a&=~($pg_namespace.SITE_TYPE_CONDUIT_SE|$pg_namespace.SITE_TYPE_SEARCH_ENGINE));return a},set_settings_url:function(b){pg_conf.global.set_str(a.STG_KEY.SETTINGS_URL,
b)},get_settings_url:function(){return pg_conf.global.get_str(a.STG_KEY.SETTINGS_URL,pg_settings.SETTINGS_FILE_URL)},set_impr_type:function(b,c){pg_conf.global.set_int(a.STG_KEY.IMPR_TYPE,b,c)},get_impr_type:function(){return pg_conf.global.get_int(a.STG_KEY.IMPR_TYPE,a.DEFAULT_IMPR_TYPE)},get_effective_impr_type:function(){var a=this.get_impr_type();pg_instance.get_ecom_search_enabled()||(a&=~$pg_namespace.IMPR_TYPE_URL_INVESTIGATION);return a},set_service_support:function(b,c){pg_conf.global.set_int(a.STG_KEY.SERVICE_SUPPORT,
b,c)},get_service_support:function(){return pg_conf.global.get_int(a.STG_KEY.SERVICE_SUPPORT,a.DEFAULT_SERVICE_SUPPORT)},set_extra_params:function(b){pg_conf.global.set_obj(a.STG_KEY.EXTRA_PARAMS,b)},get_extra_params:function(){var b=pg_conf.global.get_obj(a.STG_KEY.EXTRA_PARAMS,{});if(b instanceof Array)return{};return b},set_last_upgrade_display:function(b){pg_conf.global.set_int(a.STG_KEY.LAST_UPGRADE_DISPLAY,b)},get_last_upgrade_display:function(){return pg_conf.global.get_int(a.STG_KEY.LAST_UPGRADE_DISPLAY,
0)},set_upgrade_info:function(b,c){pg_conf.global.set_obj(a.STG_KEY.UPGRADE_INFO,b,c)},get_upgrade_info:function(){return pg_conf.global.get_obj(a.STG_KEY.UPGRADE_INFO,a.DEFAULT_UPGRADE_INFO)},should_display_upgrade_notification:function(){var a=pg_instance.get_last_upgrade_display(),c=pg_instance.get_upgrade_info();return pg_instance.is_enabled()&&c.has_new_version&&a+c.span<(new Date).valueOf()},set_client_version:function(b){pg_conf.global.set_str(a.STG_KEY.CLIENT_VERSION,b)},get_client_version:function(){return pg_conf.global.get_str(a.STG_KEY.CLIENT_VERSION,
a.DEFAULT_CLIENT_VERSION)},set_google_patch:function(b,c){pg_conf.global.set_bool(a.STG_KEY.GOOGLE_PATCH,b?!0:!1,c)},get_google_patch:function(){return pg_conf.global.get_bool(a.STG_KEY.GOOGLE_PATCH,a.DEFAULT_GOOGLE_PATCH)},set_search_engine_enabled:function(b){pg_conf.global.set_bool(a.STG_KEY.OPT_ENABLE_SEARCH_ENGINES,b)},get_search_engine_enabled:function(){return pg_conf.global.get_bool(a.STG_KEY.OPT_ENABLE_SEARCH_ENGINES,!0)},set_ecom_search_enabled:function(b){pg_conf.global.set_bool(a.STG_KEY.OPT_ENABLE_ECOMM_SEARCH,
b)},get_ecom_search_enabled:function(){return pg_conf.global.get_bool(a.STG_KEY.OPT_ENABLE_ECOMM_SEARCH,!0)},set_last_post_data:function(b){pg_conf.global.set_str(a.STG_KEY.LAST_POST_DATA,b)},get_last_post_data:function(){return pg_conf.global.get_str(a.STG_KEY.LAST_POST_DATA,"")},set_client_actions_id:function(b,c){pg_conf.global.set_str(a.STG_KEY.CLIENT_ACTIONS_ID,b,c)},get_client_actions_id:function(){return pg_conf.global.get_str(a.STG_KEY.CLIENT_ACTIONS_ID,"")},get_prefs:function(){var b={};
b[a.STG_KEY.FIRST_RUN]=this.is_first_run();b[a.STG_KEY.FIRST_RUN_TIME]=this.get_first_run_time();b[a.STG_KEY.MACHINE_ID]=this.get_machine_id();b[a.STG_KEY.USER_ID]=this.get_user_id();b[a.STG_KEY.SNOOZE_TIME]=this.get_snooze_time();b[a.STG_KEY.IS_ENABLED]=this.is_enabled();b[a.STG_KEY.USER_GROUP]=this.get_user_group();b[a.STG_KEY.SETTINGS_UPDATE_INTERVAL]=this.get_settings_update_interval();b[a.STG_KEY.OFFERS_URL]=this.get_offers_url();b[a.STG_KEY.CX_SERVER_LOCATION]=this.get_cx_server_location();
b[a.STG_KEY.LAST_SETTINGS_UPDATE]=this.get_last_settings_update();b[a.STG_KEY.SETTINGS_UPDATE_INTERVAL]=this.get_settings_update_interval();b[a.STG_KEY.SETTINGS_URL]=this.get_settings_url();b[a.STG_KEY.CATALOG_TYPE]=this.get_catalog_type();b[a.STG_KEY.COUNTRY_CODE]=this.get_country_code();b[a.STG_KEY.WL_CATALOGS_URL]=this.get_wl_catalogs_url();b[a.STG_KEY.IMPR_TYPE]=this.get_impr_type();b[a.STG_KEY.ACTIVE_SITE_TYPES]=this.get_active_site_types();b[a.STG_KEY.CLIENT_VERSION]=this.get_client_version();
b[a.STG_KEY.DIST_ID]=this.get_dist_id();b[a.STG_KEY.SUB_DIST_ID]=this.get_sub_dist_id();b[a.STG_KEY.GOOGLE_PATCH]=this.get_google_patch();return b},get_query_params:function(){var a={};a.bt=pg_settings.BROWSER_TYPE;a.bv=pg_settings.BROWSER_VERSION;a.os=pg_settings.OS;a.defbt="";a.pver=pg_settings.PROTOCOL_VERSION;a.app=pg_settings.APP_NAME;a.cver=this.get_client_version();a.cbld=$pg_namespace.CLIENT_BUILD;a.pglv=pg_settings.LOADER_VERSION;a.cnum=this.get_machine_id();a.unum=this.get_user_id();a.disid=
this.get_dist_id();a.subdisid=this.get_sub_dist_id();a.bname=pg_settings.BRAND_DISPLAY_NAME;a.cdate=this.get_first_run_time();a.ct=this.get_country_code();a.ug=this.get_user_group();a.inst=this.is_first_run()?1:0;a.ts=pg_wl_catalogger.get_timestamp();a.snz=this.is_snoozing()?1:0;a.zs=pg_settings.SUPPORTS_ZIP;a.cxt=this.get_catalog_type();a.ext_type=1;a.ctype=0;a.sp=pg_settings.SLIDER_POS;var c=this.get_extra_params(),d;for(d in c)c.hasOwnProperty(d)&&(a[d]=c[d]);return a},make_offers_url:function(a){var c=
this.get_query_params();/(^|&)impr=/.test(a)&&"impr"in c&&delete c.impr;var d=[],e;for(e in c)c.hasOwnProperty(e)&&d.push(e+"="+$pg_namespace.encodeURIComponent(c[e]));return(pg_settings.MAM_SHOW_UI==!0?this.get_offers_json_url():this.get_offers_url())+"?"+d.join("&")+(d.length>0?"&":"")+a},apply_settings:function(a,c){pg_instance.set_catalog_type(a.cxt,c);pg_instance.set_cx_server_location(a.cx_server_location,c);pg_instance.set_cx_ssl_server_location(a.cx_ssl_server_location,c);pg_instance.set_offers_url(a.s_url,
c);pg_instance.set_offers_json_url(a.s_json_url,c);pg_instance.set_settings_update_interval(a.cfg_interval,c);pg_instance.set_user_group(a.group,c);pg_instance.set_active_site_types(a.active_site_type,c);pg_instance.set_impr_type(a.impr_type,c);pg_instance.set_service_support(a.service_support,c);pg_instance.set_upgrade_info(a.upgrade_info,c);pg_instance.set_google_patch(a.google_patch,c)}}},pg_settings_class=function(){this.PG_BASE_URL="//inst.shoppingate.info/js/";this.SETTINGS_FILE_URL="//settings.shoppingate.info/settings.ashx";
this.DEFAULT_OFFERS_JSON_URL=this.DEFAULT_OFFERS_URL="//service.shoppingate.info/default.aspx";this.INJECTION_REPORT_URL="//service.shoppingate.info/inj.ashx";this.WL_FILE_KEY_PREFIX="pg_wl_";this.WL_UPDATE_QUEUE_KEY="pg_wl_update_queue";this.WL_UPDATE_TIMESTAMP_KEY="pg_wl_update_ts";this.HOST_WL_RULES_KEY_PREFIX="pg_wl_rule_";this.DEFAULT_SETTINGS_FILE_UPDATE_INTERVAL=288E5;this.DEFAULT_ACTIVE_SITE_TYPES=$pg_namespace.SERVICE_TYPE_SHOPPING|$pg_namespace.SERVICE_TYPE_TRAVEL;this.DISTRIBUTER_ID="dist-1";
this.SUB_DISTRIBUTER_ID="-";this.BRAND_DISPLAY_NAME="";this.BROWSER_VERSION=this.BROWSER_TYPE="unknown";this.OS="";this.PROTOCOL_VERSION=1;this.APP_NAME="sg_js";this.SUPPORTS_ZIP=this.LOADER_VERSION=0;this.MAM_APP_ID="";this.MAM_SHOW_UI=!1;this.EXCLUDED_SERVICE_TYPES="";this.INLINE_OFFERS=!1;this.FALLBACK_URL=this.LAST_URL="";this.DISABLE_DEBUG_WINDOW=0;this.DEFAULT_SLIDER_POS="br";this.DEFAULT_SLIDER_OFFSET=0;this.SLIDER_POS=this.DEFAULT_SLIDER_POS;this.SLIDER_OFFSET=0},pg_settings_manager_class=
function(){var a=$pg_namespace,b=a.unescape,c=[],d=0,e=function(c){try{var d={},j=xml2json(c,"");d.cxt=a.CATALOG_TYPE_WL;"cxt"in j&&parseInt(j.cxt);d.sites_rules_files={timestamp:(new Date).valueOf()/1E3,update_files:[],server_location:""};if("sites_rules_files"in j){if("@ts"in j.sites_rules_files)d.sites_rules_files.timestamp=parseInt(j.sites_rules_files["@ts"]);if("server_location"in j.sites_rules_files&&"#cdata"in j.sites_rules_files.server_location)d.sites_rules_files.server_location=j.sites_rules_files.server_location["#cdata"],
d.sites_rules_files.server_location=d.sites_rules_files.server_location.replace(/http:/i,"");if("ssl_server_location"in j.sites_rules_files&&"#cdata"in j.sites_rules_files.ssl_server_location)d.sites_rules_files.ssl_server_location=j.sites_rules_files.ssl_server_location["#cdata"],d.sites_rules_files.ssl_server_location=d.sites_rules_files.ssl_server_location.replace(/http:/i,"");if("file"in j.sites_rules_files){var e=j.sites_rules_files.file,c=function(a){var b=typeof a;if(b=="string")return a;if(b==
"object"){if("#cdata"in a)return a["#cdata"];if("#text"in a)return a["#text"]}return!1};if(e.constructor==Array)for(var g=0,h=e.length;g<h;++g){var q=c(e[g]);q!==!1&&d.sites_rules_files.update_files.push(q)}else q=c(e),q!==!1&&d.sites_rules_files.update_files.push(q)}}d.cx_server_location="";if("cx_server_location"in j&&"#cdata"in j.cx_server_location)d.cx_server_location=b(j.cx_server_location["#cdata"]),d.cx_server_location=d.cx_server_location.replace(/http:/i,"");d.cx_ssl_server_location=d.cx_server_location;
if("cx_ssl_server_location"in j&&"#cdata"in j.cx_ssl_server_location)d.cx_ssl_server_location=b(j.cx_ssl_server_location["#cdata"]),d.cx_ssl_server_location=d.cx_ssl_server_location.replace(/http:/i,"");d.s_url=pg_settings.DEFAULT_OFFERS_URL;if("s_url"in j&&"#cdata"in j.s_url)d.s_url=b(j.s_url["#cdata"]),d.s_url=d.s_url.replace(/http:/i,"");d.s_json_url=pg_settings.DEFAULT_OFFERS_JSON_URL;if("s_json_url"in j&&"#cdata"in j.s_json_url)d.s_json_url=b(j.s_json_url["#cdata"]),d.s_json_url=d.s_json_url.replace(/http:/i,
"");d.cfg_interval=pg_settings.DEFAULT_SETTINGS_FILE_UPDATE_INTERVAL;if("cfg_interval"in j)d.cfg_interval=parseInt(j.cfg_interval)*36E5;d.group=a.DEFAULT_USER_GROUP;if("group"in j&&"#cdata"in j.group)d.group=b(j.group["#cdata"]);d.active_site_type=pg_settings.DEFAULT_ACTIVE_SITE_TYPES;if("active_site_type"in j&&"#cdata"in j.active_site_type)d.active_site_type=parseInt(b(j.active_site_type["#cdata"]));d.impr_type=a.DEFAULT_IMPR_TYPE;if("impr_type"in j&&"#cdata"in j.impr_type)d.impr_type=parseInt(j.impr_type["#cdata"]);
d.service_support=a.DEFAULT_SERVICE_SUPPORT;if("service_support"in j&&"#cdata"in j.service_support)d.service_support=parseInt(j.service_support["#cdata"]);d.upgrade_info=a.DEFAULT_UPGRADE_INFO;if("upgrade_info"in j&&"new_ver"in j.upgrade_info&&"url"in j.upgrade_info&&"span"in j.upgrade_info){var o=j.upgrade_info.new_ver,m=j.upgrade_info.url,v=j.upgrade_info.span,o=typeof o=="object"&&"#cdata"in o?o["#cdata"]:o,m=typeof m=="object"&&"#cdata"in m?m["#cdata"]:b(m),v=typeof v=="object"&&"#cdata"in v?
v["#cdata"]:parseInt(v),l=pg_instance.get_upgrade_info();l.new_ver=o;l.url=m;l.span=v*36E5;l.has_new_version=f(pg_instance.get_client_version(),o)>0;d.upgrade_info=l}d.client_actions=[];d.client_actions_id="";if("client_actions"in j&&"action"in j.client_actions){var s=j.client_actions;if("@id"in s){d.client_actions_id=s["@id"];var w=s.action;w.length==void 0&&(w=[w]);for(var e=0,z=w.length;e<z;++e)d.client_actions.push(w[e])}}d.google_patch=a.DEFAULT_GOOGLE_PATCH;if("google_patch"in j)d.google_patch=
parseInt(j.google_patch)?!0:!1;d.server_time="";if("servertime"in j)d.server_time=b(j.servertime["#cdata"]);d.offers_animation_type=a.DEFAULT_OFFERS_ANIMATION_TYPE;if("offers_animation_type"in j&&"#cdata"in j.offers_animation_type)d.offers_animation_type=parseInt(j.offers_animation_type["#cdata"])}catch(x){return!1}return d},f=function(a,b){for(var c=[0,0,0],d=[0,0,0],a=a.split("."),b=b.split("."),e=0,f=a.length;e<f&&e<3;++e)c[e]=parseInt(a[e]);e=0;for(f=b.length;e<f&&e<3;++e)d[e]=parseInt(b[e]);
for(e=0;e<3;++e){if(c[e]<d[e])return 1;if(c[e]>d[e])return-1}return 0},h=function(){function a(){if(typeof g.readyState=="undefined"||g.readyState==4)try{if(typeof g.status=="undefined"||g.status==200){var b=g.responseText,b=b.replace(/<\?xml[^?]+\?>/,"");a:{var d=b;try{if(window.DOMParser){b=(new DOMParser).parseFromString(d,"text/xml");break a}else for(var j=["Msxml2.DOMDocument.3.0","Msxml2.DOMDocument"];0<j.length;){var f=new ActiveXObject(j[0]);f.async=!1;f.loadXML(d);f.setProperty("SelectionLanguage",
"XPath");b=f;break a}}catch(q){}b=null}var h=e(b);if(h){pg_instance.set_last_settings_update((new Date).valueOf(),!0);l();for(var b=0,r=c.length;b<r;++b)c[b].on_settings_update(h)}}}catch(n){}}var b=pg_instance.get_query_params(),d=pg_instance.get_client_actions_id();if(d.length>0)b.cai=d;var d=[],f;for(f in b)b.hasOwnProperty(f)&&d.push(f+"="+$pg_namespace.encodeURIComponent(b[f]));var g=new XMLHttpRequest;try{var h=pg_instance.get_settings_url()+"?"+d.join("&");g.responseType===void 0&&typeof XDomainRequest!==
"undefined"?(g=new XDomainRequest,g.onload=a,g.ontimeout=function(){},g.onprogress=function(){},g.timeout=9E3):g.onreadystatechange=a;g.onerror=function(){};g.open("GET",h,!0);g.send()}catch(q){}},g=function(a){d&&(window.clearTimeout(d),d=0);a>=0&&(d=window.setTimeout(h,a))},l=function(){var a=pg_instance.get_settings_update_interval(),b=(new Date).valueOf(),b=pg_instance.get_last_settings_update()+a-b;return b<0||b>a?0:b+Math.floor(Math.random()*100)*1E3};return{init:function(){l()==0?g(0):g(-1)},
add_listener:function(a){this.remove_listener(a);c.push(a)},remove_listener:function(a){for(var b=0,d=c.length;b<d;++b)if(a===c[b]){c.splice(b,1);break}},reset:function(){g(0)},reschedule:function(){}}},pg_wl_catalogger_class=function(a){var b=0,c=function(){for(var a=["1.txt","wlu.txt"],b="a".charCodeAt(0),c="z".charCodeAt(0);b<=c;++b)a.push(String.fromCharCode(b)+".txt");return a},d=function(a){a=a.toLowerCase().replace(/^www\./,"");if(a=="")return!1;a=""+a.charAt(0);if(/[0-9]/.test(a))return"1.txt";
if(/[a-z]/.test(a))return a+".txt";return!1},e=function(a,b){try{var c=pg_settings.WL_FILE_KEY_PREFIX+a;if(a=="wlu.txt"||a=="1.txt"){var d=pg_conf.global.get(c);if(!d)return;var d=JSON.parse(d),e;for(e in d)pg_conf.global.del(pg_settings.HOST_WL_RULES_KEY_PREFIX+e,!0)}else{var g=""+a.charAt(0),f=pg_settings.HOST_WL_RULES_KEY_PREFIX+g;for(key in pg_conf.global.cache)key.indexOf(f)==0&&pg_conf.global.del(key,!0)}b||pg_conf.global.commit()}catch(h){}},f=function(a){function c(){if(typeof f.readyState==
"undefined"||f.readyState==4){var d=!1;try{if(typeof f.status=="undefined"||f.status==200){var q=$pg_namespace.decode(f.responseText),h;a:{var r=a,s=!1;try{for(var t=q.split("\n"),s={},q=0,p=t.length;q<p;++q)if(t[q].length!=0){var x=t[q].split("=");x.length==2&&(s[x[0]]=x[1])}var y=pg_settings.WL_FILE_KEY_PREFIX+r;e(r,!0);pg_conf.global.set(y,$pg_namespace.stringify(s),!0)}catch(A){h=!1;break a}h=s}d=!1!==h}}catch(C){}h=a;b+=d?0:1;d=g();h=d.files.indexOf(h);h!=-1&&(d.files.splice(h,1),l(d,!0));pg_conf.global.commit();
d.files.length&&n()}}var d;d=window.location.protocol=="https:"?pg_instance.get_wl_catalogs_ssl_url():pg_instance.get_wl_catalogs_url();d=[d,a].join("/");var f=new XMLHttpRequest;f.responseType===void 0&&typeof XDomainRequest!=="undefined"?(f=new XDomainRequest,f.ontimeout=function(){},f.onprogress=function(){},f.timeout=9E3,f.onload=c):f.onreadystatechange=c;f.onerror=function(){};try{f.open("GET",d,!0),f.send()}catch(q){}},h=function(a){this.download_callback=a;this.wl_updates={};if(a=pg_conf.global.get(pg_settings.WL_FILE_KEY_PREFIX+
"wlu.txt"))this.wl_updates=JSON.parse(a)};h.prototype.next_host=function(a){a=a.split(".");if(a.length>2)return a.shift(),a.join(".");return""};h.prototype.get_rule=function(a){for(a=a.toLowerCase().replace("www.","");a!="";){var b=0,c=d(a),c=JSON.parse(pg_conf.global.get(pg_settings.WL_FILE_KEY_PREFIX+c));this.wl_updates&&a in this.wl_updates?b=this.wl_updates[a]:c&&a in c&&(b=c[a]);if(b){if(c=pg_conf.global.get(pg_settings.HOST_WL_RULES_KEY_PREFIX+a)){var c=c.replace(/[\\]{1}\'/,"\\\\'"),c=JSON.parse(c),
e=(new Date).valueOf();"@last_check"in c||(c["@last_check"]=0);"@last_modified"in c||(c["@last_modified"]=e);var f="@ttl"in c?parseInt(c["@ttl"]):24;f*=36E5;e-c["@last_check"]>f&&window.setTimeout(function(c){return function(){c.download_rule(a,b)}}(this),100);return c}window.setTimeout(function(c){return function(){c.download_rule(a,b)}}(this),100);break}else a=this.next_host(a)}return null};h.prototype.download_rule=function(a,b){function c(){if(typeof f.readyState=="undefined"||f.readyState==4)try{if(typeof f.status==
"undefined"||f.status==200){var a=$pg_namespace.decode(f.responseText),a=a.replace(/<\?xml[^?]+\?>/,""),b;a:{try{if(window.DOMParser){b=(new DOMParser).parseFromString(a,"text/xml");break a}else for(var d=["Msxml2.DOMDocument.3.0","Msxml2.DOMDocument"];0<d.length;){var j=new ActiveXObject(d[0]);j.async=!1;j.loadXML(a);j.setProperty("SelectionLanguage","XPath");b=j;break a}}catch(g){}b=null}var h=b.getElementsByTagName("rule");if(h.length>0){var l=h[0],n=l.getAttribute("name"),r=xml2json(l,"");r["@last_check"]=
(new Date).valueOf();r["@last_modified"]=(new Date).valueOf();r=$pg_namespace.unescape($pg_namespace.stringify(r));pg_conf.global.set(pg_settings.HOST_WL_RULES_KEY_PREFIX+n,r);e.rule=r;e.download_callback&&e.download_callback()}}}catch(p){}}var d;d=window.location.protocol=="https:"?pg_instance.get_cx_ssl_server_location()+"/"+b.substring(b.length-2)+"/"+b+".txt":pg_instance.get_cx_server_location()+"/"+b.substring(b.length-2)+"/"+b+".txt";var e=this,f=new XMLHttpRequest;f.responseType===void 0&&
typeof XDomainRequest!=="undefined"?(f=new XDomainRequest,f.onload=c,f.ontimeout=function(){},f.onprogress=function(){},f.timeout=9E3):f.onreadystatechange=c;f.onerror=function(){};f.open("GET",d,!0);f.send()};var g=function(){var a=pg_conf.global.get(pg_settings.WL_UPDATE_QUEUE_KEY);try{a=JSON.parse(a)}catch(b){a=null}if(a==null||!("ts"in a)||!("files"in a))a={ts:0,files:[]};return a},l=function(a,b){if(typeof a!="object"||!("ts"in a)||!("files"in a))a.ts=0,a.files=[];a.files.length==0&&pg_conf.global.set(pg_settings.WL_UPDATE_TIMESTAMP_KEY,
a.ts.toString(),!0);pg_conf.global.set(pg_settings.WL_UPDATE_QUEUE_KEY,$pg_namespace.stringify(a),b)},n=function(){var a=[1,5,30,60];window.setTimeout(p,1E3*a[Math.min(a.length-1,b)])},p=function(){var a=g(),b=a.files.length;b&&(a=a.files.splice(Math.random()*b,1),f(a[0]))};return{init:function(){n()},get_rule:function(b){return(new h(a)).get_rule(b)},reset_catalogs:function(){c().forEach(function(a){var b=pg_settings.WL_FILE_KEY_PREFIX+a;e(a,!0);pg_conf.global.del(b,!0)});pg_conf.global.del(pg_settings.WL_UPDATE_TIMESTAMP_KEY,
!0);pg_conf.global.commit()},get_timestamp:function(){var a=pg_conf.global.get(pg_settings.WL_UPDATE_TIMESTAMP_KEY);a||(a=0);return parseInt(a)},settings_update:function(a){var b=a.sites_rules_files,c=b.timestamp,a=b.update_files,d=b.ssl_server_location;pg_instance.set_wl_catalogs_url(b.server_location,!0);pg_instance.set_wl_catalogs_ssl_url(d,!0);b=g();b.ts=c;c=0;for(d=a.length;c<d;++c){var e=a[c].toLowerCase().replace(".xml",".txt");-1==b.files.indexOf(e)&&b.files.push(e)}l(b,!0);p()}}},pg_wl_catalogger_class_ie=
function(a){var b=0,c=0,d=function(){for(var a=["1.txt","wlu.txt"],b="a".charCodeAt(0),c="z".charCodeAt(0);b<=c;++b)a.push(String.fromCharCode(b)+".txt");return a},e=function(a){a=a.toLowerCase().replace(/^www\./,"");if(a=="")return!1;a=""+a.charAt(0);if(/[0-9]/.test(a))return"1.txt";if(/[a-z]/.test(a))return a+".txt";return!1},f=function(a,b){try{var c=pg_settings.WL_FILE_KEY_PREFIX+a;if(a=="wlu.txt"||a=="1.txt"){var d=pg_conf.global.get(c);if(!d)return;var d=JSON.parse(d),e;for(e in d)pg_conf.global.del(pg_settings.HOST_WL_RULES_KEY_PREFIX+
e,!0)}else{var f=""+a.charAt(0),g=pg_settings.HOST_WL_RULES_KEY_PREFIX+f;for(key in pg_conf.global.cache)key.indexOf(g)==0&&pg_conf.global.del(key,!0)}b||pg_conf.global.commit()}catch(h){}},h=function(a){function b(){if(typeof d.readyState=="undefined"||d.readyState==4){var c=!1;try{if(typeof d.status=="undefined"||d.status==200){var e=$pg_namespace.decode(d.responseText),h;a:{var j=a,l=!1;try{for(var m=e.split("\n"),l={},e=0,o=m.length;e<o;++e)if(m[e].length!=0){var n=m[e].split("=");n.length==2&&
(l[n[0]]=n[1])}var p=pg_settings.WL_FILE_KEY_PREFIX+j;f(j,!0);pg_conf.global.set(p,$pg_namespace.stringify(l))}catch(B){h=!1;break a}h=l}c=!1!==h}}catch(r){}g(c,d.status,a)}}var c;c=window.location.protocol=="https:"?pg_instance.get_wl_catalogs_ssl_url():pg_instance.get_wl_catalogs_url();c=[c,a].join("/");var d=new XMLHttpRequest;d.responseType===void 0&&typeof XDomainRequest!=="undefined"?(d=new XDomainRequest,d.ontimeout=function(){},d.onprogress=function(){},d.timeout=9E3,d.onload=b):d.onreadystatechange=
b;d.onerror=function(){};try{d.open("GET",c,!0),d.send()}catch(e){}},g=function(a,c,d){b+=a?0:1;p(function(a){if(a&&a.ownLock){var b=a.files.indexOf(d);b!=-1&&(a.files.splice(b,1),j(a));a.files.length&&r(a)}})},l=function(a){this.download_callback=a;this.wl_updates={};if(a=pg_conf.global.get(pg_settings.WL_FILE_KEY_PREFIX+"wlu.txt"))this.wl_updates=JSON.parse(a)};l.prototype.next_host=function(a){a=a.split(".");if(a.length>2)return a.shift(),a.join(".");return""};l.prototype.get_rule=function(a){for(a=
a.toLowerCase().replace("www.","");a!="";){var b=0,c=e(a),c=JSON.parse(pg_conf.global.get(pg_settings.WL_FILE_KEY_PREFIX+c));this.wl_updates&&a in this.wl_updates?b=this.wl_updates[a]:c&&a in c&&(b=c[a]);if(b){if(c=pg_conf.global.get(pg_settings.HOST_WL_RULES_KEY_PREFIX+a)){var c=c.replace(/[\\]{1}\'/,"\\\\'"),c=JSON.parse(c),d=(new Date).valueOf();"@last_check"in c||(c["@last_check"]=0);"@last_modified"in c||(c["@last_modified"]=d);var f="@ttl"in c?parseInt(c["@ttl"]):24;f*=36E5;d-c["@last_check"]>
f&&window.setTimeout(function(c){return function(){c.download_rule(a,b)}}(this),100);return c}window.setTimeout(function(c){return function(){c.download_rule(a,b)}}(this),100);break}else a=this.next_host(a)}return null};l.prototype.download_rule=function(a,b){function c(){if(typeof f.readyState=="undefined"||f.readyState==4)try{if(typeof f.status=="undefined"||f.status==200){var a=$pg_namespace.decode(f.responseText),a=a.replace(/<\?xml[^?]+\?>/,""),b;a:{try{if(window.DOMParser){b=(new DOMParser).parseFromString(a,
"text/xml");break a}else for(var d=["Msxml2.DOMDocument.3.0","Msxml2.DOMDocument"];0<d.length;){var g=new ActiveXObject(d[0]);g.async=!1;g.loadXML(a);g.setProperty("SelectionLanguage","XPath");b=g;break a}}catch(h){}b=null}var j=b.getElementsByTagName("rule");if(j.length>0){var l=j[0];n(l);var q=l.getAttribute("name"),o=xml2json(l,"");o["@last_check"]=(new Date).valueOf();o["@last_modified"]=(new Date).valueOf();o=$pg_namespace.unescape($pg_namespace.stringify(o));pg_conf.global.set(pg_settings.HOST_WL_RULES_KEY_PREFIX+
q,o);e.rule=o;e.download_callback&&e.download_callback()}}}catch(m){}}var d;d=window.location.protocol=="https:"?pg_instance.get_cx_ssl_server_location()+"/"+b.substring(b.length-2)+"/"+b+".txt":pg_instance.get_cx_server_location()+"/"+b.substring(b.length-2)+"/"+b+".txt";var e=this,f=new XMLHttpRequest;f.responseType===void 0&&typeof XDomainRequest!=="undefined"?(f=new XDomainRequest,f.onload=c,f.ontimeout=function(){},f.onprogress=function(){},f.timeout=9E3):f.onreadystatechange=c;f.onerror=function(){};
f.open("GET",d,!0);f.send()};var n=function(a){try{if(document.documentMode&&!(document.documentMode<11)){var b=function(a){for(var c=0;c<a.childNodes.length;c++){var d=a.childNodes[c];if(d.nodeType==Node.CDATA_SECTION_NODE){for(var e=a.textContent;a.childNodes.length>1;)a.removeChild(a.lastChild);d.textContent=e}else b(d)}};b(a)}}catch(c){}},p=function(a){pg_conf.global.getNoCache(pg_settings.WL_UPDATE_QUEUE_KEY,function(b){try{b=JSON.parse(b)}catch(d){b=null}if(b==null||!("ts"in b)||!("files"in
b))b={ts:0,files:[],lock:0};var e;e=b.lock;e=e!=0&&!(e+1E4<(new Date).valueOf())&&e!=c?!1:!0;b.ownLock=e;a(b)})},j=function(a){a.files.length==0&&pg_conf.global.set(pg_settings.WL_UPDATE_TIMESTAMP_KEY,a.ts.toString());c=(new Date).valueOf();a.lock=c;pg_conf.global.setNoCache(pg_settings.WL_UPDATE_QUEUE_KEY,$pg_namespace.stringify(a))},r=function(a){var c=[1,5,30,60],c=1E3*c[Math.min(c.length-1,b)];window.setTimeout(function(a){return function(){t(a)}}(a),c)},t=function(a){var b=a.files.length;b&&
(a=a.files.splice(Math.random()*b,1),h(a[0]))},u=function(a){var b=a.timestamp,c=a.update_files,d=a.ssl_server_location;pg_instance.set_wl_catalogs_url(a.server_location,!0);pg_instance.set_wl_catalogs_ssl_url(d);p(function(a){if(a&&a.ownLock){a.ts=b;for(var d=0,e=c.length;d<e;++d){var f=c[d].toLowerCase().replace(".xml",".txt");-1==a.files.indexOf(f)&&a.files.push(f)}j(a);t(a)}})};return{init:function(){p(function(a){a&&a.ownLock&&r(a)})},get_rule:function(b){return(new l(a)).get_rule(b)},reset_catalogs:function(){d().forEach(function(a){var b=
pg_settings.WL_FILE_KEY_PREFIX+a;f(a,!0);pg_conf.global.del(b,!0)});pg_conf.global.del(pg_settings.WL_UPDATE_TIMESTAMP_KEY,!0);pg_conf.global.commit()},get_timestamp:function(){var a=pg_conf.global.get(pg_settings.WL_UPDATE_TIMESTAMP_KEY);a||(a=0);return parseInt(a)},settings_update:function(a){u(a.sites_rules_files)}}};
$pg_namespace.pg_settings_listener={on_settings_update:function(a){pg_instance.is_first_run()&&(pg_instance.set_first_run_time(a.server_time,!0),pg_instance.set_first_run(!1,!0));pg_instance.apply_settings(a,!0);pg_conf.global.commit()&&pg_wl_catalogger.settings_update(a);execute_client_actions(a.client_actions,a.client_actions_id,!0);pg_conf.global.commit()}};
function execute_client_actions(a,b,c){try{for(var d=0,e=a.length;d<e;++d){var f=a[d];if(!1 in f)return!1;var h=f["@type"];if(h=="reset_client"){for(g in pg_conf.global.cache)g!=$pg_namespace.STG_KEY.MACHINE_ID&&g!=$pg_namespace.STG_KEY.USER_ID&&g!=$pg_namespace.STG_KEY.USER_IDUSER_GROUP&&g!=$pg_namespace.STG_KEY.FIRST_RUN&&g!=$pg_namespace.STG_KEY.CLIENT_ACTIONS_ID&&pg_conf.global.del(g,!0);pg_conf.global.commit()}else if(h=="del_reg_key"){if(!1 in f)return!1;var g=f.key,g=typeof g=="object"&&"#cdata"in
g?g["#cdata"]:g;pg_conf.global.del(g)}else if(h=="set_reg_val"){if(!1 in f)return!1;g=f.key;g=typeof g=="object"&&"#cdata"in g?g["#cdata"]:g;if(!1 in f)return!1;var l=f.value,l=typeof l=="object"&&"#cdata"in l?l["#cdata"]:l;pg_conf.global.set(g,l)}else if(h=="set_extra_param"){if(!1 in f)return!1;var n=f.name,n=typeof n=="object"&&"#cdata"in n?n["#cdata"]:n;if(!1 in f)return!1;var l=f.value,l=typeof l=="object"&&"#cdata"in l?l["#cdata"]:l,p=pg_instance.get_extra_params();p[n]=l;pg_instance.set_extra_params(p)}else if(h==
"del_extra_param"){if(!1 in f)return!1;n=f.name;n=typeof n=="object"&&"#cdata"in n?n["#cdata"]:n;p=pg_instance.get_extra_params();delete p[n];pg_instance.set_extra_params(p)}else if(h=="custom_action"){if(!1 in f)return!1;var j=f.js,j=typeof j=="object"&&"#cdata"in j?j["#cdata"]:j;eval(j)}}pg_instance.set_client_actions_id(b,c)}catch(r){}}
$pg_namespace.BrowserDetect={isIE:function(){return this.browser=="Explorer"},isFF:function(){return this.browser=="Firefox"},isSafari:function(){return this.browser=="Safari"},isChrome:function(){return this.browser=="Chrome"},init:function(){this.browser=this.searchString(this.dataBrowser)||"unknown";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"unknown";this.OS=this.searchString(this.dataOS)||"unknown"},searchString:function(a){for(var b=0;b<a.length;b++){var c=
a[b].string,d=a[b].prop;this.versionSearchString=a[b].versionSearch||a[b].identity;if(c){if(c.indexOf(a[b].subString)!=-1)return a[b].identity}else if(d)return a[b].identity}},searchVersion:function(a){var b=a.indexOf(this.versionSearchString);if(b!=-1)return parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,
subString:"Trident",identity:"Explorer",versionSearch:"rv"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",
identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,
subString:"Linux",identity:"Linux"}]};$pg_namespace.fixDistributerAndSubDistributer=function(){pg_settings.DISTRIBUTER_ID=pg_settings.DISTRIBUTER_ID.replace(/pricegong/gi,"Shoppingate");pg_settings.SUB_DISTRIBUTER_ID=pg_settings.SUB_DISTRIBUTER_ID.replace(/pricegong/gi,"Shoppingate");pg_settings.BRAND_DISPLAY_NAME=pg_settings.BRAND_DISPLAY_NAME.replace(/pricegong/gi,"Shoppingate")};
$pg_namespace.setInstanceInfo=function(){$pg_namespace.BrowserDetect.init();pg_settings.BROWSER_TYPE=$pg_namespace.BrowserDetect.isIE()?"ie":$pg_namespace.BrowserDetect.isFF()?"ff":$pg_namespace.BrowserDetect.isChrome()?"ch":$pg_namespace.BrowserDetect.isSafari()?"sf":"unknown";pg_settings.BROWSER_VERSION=$pg_namespace.BrowserDetect.version;pg_settings.OS=$pg_namespace.BrowserDetect.OS;if(typeof SG_JS_AFFILIATE_ID!=="undefined"){pg_settings.DISTRIBUTER_ID=SG_JS_AFFILIATE_ID;if(typeof SG_JS_SUB_AFFILIATE_ID!==
"undefined")pg_settings.SUB_DISTRIBUTER_ID=SG_JS_SUB_AFFILIATE_ID;if(typeof SG_JS_BRAND_DISPLAY_NAME!=="undefined")pg_settings.BRAND_DISPLAY_NAME=SG_JS_BRAND_DISPLAY_NAME;if(typeof SG_JS_FALLBACK_URL!=="undefined")pg_settings.FALLBACK_URL=SG_JS_FALLBACK_URL;if(typeof SG_JS_SLIDER_POS!=="undefined")pg_settings.SLIDER_POS=SG_JS_SLIDER_POS;if(typeof SG_JS_SLIDER_OFFSET!=="undefined")pg_settings.SLIDER_OFFSET=SG_JS_SLIDER_OFFSET;$pg_namespace.fixDistributerAndSubDistributer()}else try{if(typeof conduit!==
"undefined"&&typeof conduit.valueApps!=="undefined")pg_settings.APP_NAME="pg_js",pg_settings.DISTRIBUTER_ID="cndtjs",pg_settings.PG_BASE_URL="//inst.pricegong.com/js/",pg_settings.SETTINGS_FILE_URL="//settings.pricegong.com/settings.ashx",pg_settings.DEFAULT_OFFERS_URL="//service.pricegong.com/default.aspx",pg_settings.DEFAULT_OFFERS_JSON_URL="//service.pricegong.com/default.aspx",pg_settings.INJECTION_REPORT_URL="//service.pricegong.com/inj.ashx";var a=$pg_namespace.StringFormat("script[src*='{0}']",
pg_settings.PG_BASE_URL+$pg_namespace.SG_BG_FILE_NAME),b=document.querySelector(a);if(b){var c=b.src;if(c&&typeof c==="string"){a=function(a,b,c){return decodeURI((RegExp(a+"=(.+?)(&|$)").exec(b)||[,c])[1])};if(pg_settings.DISTRIBUTER_ID=="cndtjs"){var d=a("ui",c),d=parseInt(d);pg_settings.MAM_SHOW_UI=isNaN(d)?!1:d==1;pg_settings.MAM_APP_ID=a("appId",c);pg_settings.BRAND_DISPLAY_NAME="PriceGong";conduit.valueApps.getMamId(function(a){pg_settings.SUB_DISTRIBUTER_ID=a})}else pg_settings.DISTRIBUTER_ID=
a("AFFILIATE_ID",c,pg_settings.DISTRIBUTER_ID),pg_settings.SUB_DISTRIBUTER_ID=a("SUB_DISTRIBUTER_ID",c,pg_settings.SUB_DISTRIBUTER_ID),pg_settings.BRAND_DISPLAY_NAME=a("BRAND_DISPLAY_NAME",c,pg_settings.BRAND_DISPLAY_NAME),pg_settings.EXCLUDED_SERVICE_TYPES=a("EXCLUDED_SERVICE_TYPES",c,""),pg_settings.FALLBACK_URL=decodeURIComponent(a("FALLBACK_URL",c,"")),pg_settings.SLIDER_POS=decodeURIComponent(a("SLIDER_POS",c,pg_settings.DEFAULT_SLIDER_POS)),pg_settings.SLIDER_OFFSET=decodeURIComponent(a("SLIDER_OFFSET",
c,pg_settings.DEFAULT_SLIDER_OFFSET)),pg_settings.SLIDER_OFFSET=parseInt(pg_settings.SLIDER_OFFSET),pg_settings.DISABLE_DEBUG_WINDOW=a("DISABLE_DEBUG_WINDOW",c,pg_settings.DISABLE_DEBUG_WINDOW),pg_settings.DISABLE_DEBUG_WINDOW=parseInt(pg_settings.DISABLE_DEBUG_WINDOW),$pg_namespace.fixDistributerAndSubDistributer();var e=a("INLINE_OFFERS",c,0),e=parseInt(e);pg_settings.INLINE_OFFERS=e==1}}}catch(f){}};
$pg_namespace.showOfferFromRule=function(a,b){typeof $pg_namespace.doc_agent=="undefined"||$pg_namespace.doc_agent==null||$pg_namespace.doc_agent.showOfferFromRule(a,b)};$pg_namespace.showCouponsFromRule=function(a){typeof $pg_namespace.doc_agent=="undefined"||$pg_namespace.doc_agent==null||$pg_namespace.doc_agent.showCouponsFromRule(a)};
$pg_namespace.injectInlineOffers=function(){if(pg_settings.INLINE_OFFERS!=!1){var a=document.createElement("script");a.type="text/javascript";a.src="http://ig.tokido.me:8080/adserver/static/js/inimage_i.js?pid=160&ext_domain=1&cb="+Math.round((new Date).getTime()/1E3);try{document.getElementsByTagName("head")[0].appendChild(a)}catch(b){try{document.body.appendChild(a)}catch(c){}}}};
$pg_namespace.retryPageInvestigate=function(){try{typeof $pg_namespace.doc_agent!=="undefined"&&$pg_namespace.doc_agent.valid_request==!1&&$pg_namespace.doc_agent.page_investigate()}catch(a){}};$pg_namespace.ensureJQueryExist=function(){try{if(!(typeof jQuery!="undefined"&&jQuery.fn&&jQuery.fn.animate)){var a=document.createElement("script");a.setAttribute("src","//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js");document.body.appendChild(a)}}catch(b){}};
$pg_namespace.checkFallback=function(){try{if($pg_namespace.doc_agent.valid_request!=!0&&pg_settings.FALLBACK_URL.length!=0){$pg_namespace.doc_agent.valid_request=!0;var a=document.createElement("script");a.type="text/javascript";a.src=pg_settings.FALLBACK_URL;try{document.getElementsByTagName("head")[0].appendChild(a)}catch(b){try{document.body.appendChild(a)}catch(c){}}}}catch(d){}};
$pg_namespace.injectReport=function(){function a(){}if(Math.floor(Math.random()*10)==0){var b=new XMLHttpRequest;try{b.responseType===void 0&&typeof XDomainRequest!=="undefined"?(b=new XDomainRequest,b.onload=a,b.ontimeout=function(){},b.onprogress=function(){},b.timeout=9E3):b.onreadystatechange=a;b.onerror=function(){};var c=window.location.host,d=c.indexOf(":");d!=-1&&(c=c.substring(0,d));var e=$pg_namespace.StringFormat("{0}?app={1}&cver={2}&bt={3}&bv={4}&os={5}&disid={6}&subdisid={7}&domain={8}&cb={9}",
pg_settings.INJECTION_REPORT_URL,pg_settings.APP_NAME,$pg_namespace.DEFAULT_CLIENT_VERSION,pg_settings.BROWSER_TYPE,pg_settings.BROWSER_VERSION,pg_settings.OS,pg_settings.DISTRIBUTER_ID,pg_settings.SUB_DISTRIBUTER_ID,c,(new Date).valueOf());b.open("GET",e,!0);b.send()}catch(f){}}};
$pg_namespace.init_logger=function(){try{if(typeof $pg_logging==="undefined"||$pg_logging)typeof windowId!=="undefined"&&document.title=="log4javascript"?$pg_namespace.is_log4javascriptWindow=!0:pg_logger?$pg_namespace.logger=pg_logger:($pg_namespace.logger=new pg_logger_class,pg_logger=$pg_namespace.logger,pg_settings.DISABLE_DEBUG_WINDOW==0&&$pg_namespace.logger.init())}catch(a){}};
$pg_namespace.start=function(){if(typeof pg_conf=="undefined"||pg_conf==null)try{if(typeof a==="undefined")var a=!1;if(window==window.parent&&document.URL.toLowerCase().indexOf("http")===0&&(pg_settings=new pg_settings_class,$pg_namespace.setInstanceInfo(),$pg_namespace.init_logger(),$pg_namespace.is_log4javascriptWindow!=!0)){$pg_namespace.ensureJQueryExist();$pg_namespace.injectReport();addListener(window,"load",function(){$pg_namespace.retryPageInvestigate()},!1);pg_conf=new pg_conf_class;pg_instance=
new pg_instance_class;pg_settings_manager=new pg_settings_manager_class;pg_wl_catalogger=$pg_namespace.BrowserDetect.isIE()?new pg_wl_catalogger_class_ie(function(){$pg_namespace.retryPageInvestigate()}):new pg_wl_catalogger_class(function(){$pg_namespace.retryPageInvestigate()});var b=pg_settings.DISTRIBUTER_ID!="cndtjs";$pg_namespace.injectInlineOffers();pg_conf.init(!0,b,8,function(){pg_settings_manager.init();pg_settings_manager.add_listener($pg_namespace.pg_settings_listener);pg_wl_catalogger.init();
pg_settings.LAST_URL=document.URL;if(document.URL.indexOf("inst.shoppingate.info/js/pg_debug.html")!==-1)$pg_debug.pg_refresh_prefs();else if(pg_instance.is_active())$pg_namespace.doc_agent=new $pg_namespace.page_handler(document),$pg_namespace.doc_agent.page_investigate(),$pg_namespace.checkFallback()})}}catch(c){}else if($pg_namespace.init_logger(),pg_settings.LAST_URL!=document.URL)pg_settings.LAST_URL=document.URL,$pg_namespace.BrowserDetect.init(),$pg_namespace.doc_agent=new $pg_namespace.page_handler(document),
$pg_namespace.doc_agent.page_investigate()};$pg_namespace.is_log4javascriptWindow=!1;if(typeof pg_conf=="undefined"||pg_conf==null)var pg_logger=null,pg_settings=null,pg_conf=null,pg_instance=null,pg_settings_manager=null,pg_wl_catalogger=null;$pg_namespace.start();
